// @ts-nocheck — static fallback data, types are flexible
import type {
	AgentInfo,
	CiDeepResponse,
	CiStatusResponse,
	CiSummaryResponse,
	CiTemplatesResponse,
	CrossSyncResponse,
	DeploysStatusResponse,
	ExternalAgentsResponse,
	HealthResponse,
	HooksResponse,
	HydraScoresResponse,
	HydraTask,
	LenovoStatusResponse,
	McpResponse,
	MemoryResponse,
	MetricsResponse,
	NotificationConfig,
	NotificationEvent,
	OpenclawDetailsResponse,
	OpenclawResponse,
	ProjectsResponse,
	RuleInfo,
	SkillsResponse,
	SyncResponse,
	SyncStatusResponse,
	SystemResponse,
	WatcherResponse,
} from "./api";

// ── Agents ────────────────────────────────────────────────────────────────────

const agents: AgentInfo[] = [
	{
		name: "gsd-executor",
		description: "GSD executor agent",
		category: "gsd",
		tools: ["Bash", "Read", "Write", "Edit"],
		file: "gsd-executor.md",
	},
	{
		name: "gsd-planner",
		description: "GSD planner agent",
		category: "gsd",
		tools: ["Bash", "Read", "Write"],
		file: "gsd-planner.md",
	},
	{
		name: "gsd-verifier",
		description: "GSD verifier agent",
		category: "gsd",
		tools: ["Bash", "Read"],
		file: "gsd-verifier.md",
	},
	{
		name: "gsd-debugger",
		description: "GSD debugger agent",
		category: "gsd",
		tools: ["Bash", "Read", "Write"],
		file: "gsd-debugger.md",
	},
	{
		name: "gsd-roadmapper",
		description: "GSD roadmapper agent",
		category: "gsd",
		tools: ["Bash", "Read", "Write"],
		file: "gsd-roadmapper.md",
	},
	{
		name: "gsd-phase-researcher",
		description: "GSD phase researcher",
		category: "gsd",
		tools: ["Bash", "Read"],
		file: "gsd-phase-researcher.md",
	},
	{
		name: "gsd-project-researcher",
		description: "GSD project researcher",
		category: "gsd",
		tools: ["Bash", "Read"],
		file: "gsd-project-researcher.md",
	},
	{
		name: "gsd-plan-checker",
		description: "GSD plan checker",
		category: "gsd",
		tools: ["Read"],
		file: "gsd-plan-checker.md",
	},
	{
		name: "gsd-integration-checker",
		description: "GSD integration checker",
		category: "gsd",
		tools: ["Bash", "Read"],
		file: "gsd-integration-checker.md",
	},
	{
		name: "gsd-codebase-mapper",
		description: "GSD codebase mapper",
		category: "gsd",
		tools: ["Bash", "Read"],
		file: "gsd-codebase-mapper.md",
	},
	{
		name: "gsd-research-synthesizer",
		description: "GSD research synthesizer",
		category: "gsd",
		tools: ["Read", "Write"],
		file: "gsd-research-synthesizer.md",
	},
	{
		name: "code-reviewer",
		description: "L10+ 16-dimension code review",
		category: "quality",
		tools: ["Read", "Bash"],
		file: "code-reviewer.md",
	},
	{
		name: "reality-checker",
		description: "Reality check agent",
		category: "quality",
		tools: ["Bash", "Read"],
		file: "reality-checker.md",
	},
	{
		name: "accessibility-agent",
		description: "Accessibility audit agent",
		category: "quality",
		tools: ["Bash", "Read"],
		file: "accessibility-agent.md",
	},
	{
		name: "api-contract",
		description: "API contract validator",
		category: "quality",
		tools: ["Read", "Bash"],
		file: "api-contract.md",
	},
	{
		name: "security-auditor",
		description: "Security audit agent",
		category: "security",
		tools: ["Bash", "Read", "Write"],
		file: "security-auditor.md",
	},
	{
		name: "agentic-security-auditor",
		description: "Agentic security validator",
		category: "security",
		tools: ["Bash", "Read"],
		file: "agentic-security-auditor.md",
	},
	{
		name: "dependency",
		description: "Dependency audit agent",
		category: "security",
		tools: ["Bash", "Read"],
		file: "dependency.md",
	},
	{
		name: "bundle-analyzer",
		description: "Bundle size analyzer",
		category: "performance",
		tools: ["Bash", "Read"],
		file: "bundle-analyzer.md",
	},
	{
		name: "perf-analyzer",
		description: "Performance analyzer",
		category: "performance",
		tools: ["Bash", "Read"],
		file: "perf-analyzer.md",
	},
	{
		name: "db-perf-analyzer",
		description: "Database performance agent",
		category: "performance",
		tools: ["Bash", "Read"],
		file: "db-perf-analyzer.md",
	},
	{
		name: "load-test-runner",
		description: "Load testing agent",
		category: "performance",
		tools: ["Bash"],
		file: "load-test-runner.md",
	},
	{
		name: "lighthouse-auditor",
		description: "Lighthouse performance audit",
		category: "performance",
		tools: ["Bash", "Read"],
		file: "lighthouse-auditor.md",
	},
	{
		name: "test-generator",
		description: "Test generation agent",
		category: "testing",
		tools: ["Read", "Write", "Bash"],
		file: "test-generator.md",
	},
	{
		name: "test-mega-orchestrator",
		description: "Mega test suite agent",
		category: "testing",
		tools: ["Read", "Write", "Bash"],
		file: "test-mega-orchestrator.md",
	},
	{
		name: "race-test-runner",
		description: "Race condition tester",
		category: "testing",
		tools: ["Bash", "Read"],
		file: "race-test-runner.md",
	},
	{
		name: "experiment-tracker",
		description: "Experiment runner",
		category: "testing",
		tools: ["Bash", "Read", "Write"],
		file: "experiment-tracker.md",
	},
	{
		name: "devops",
		description: "DevOps automation agent",
		category: "infrastructure",
		tools: ["Bash", "Read", "Write", "Edit"],
		file: "devops.md",
	},
	{
		name: "migration",
		description: "Database migration agent",
		category: "infrastructure",
		tools: ["Bash", "Read", "Write"],
		file: "migration.md",
	},
	{
		name: "release-manager",
		description: "Release manager agent",
		category: "infrastructure",
		tools: ["Bash", "Read", "Write"],
		file: "release-manager.md",
	},
	{
		name: "mcp-builder",
		description: "MCP server builder",
		category: "infrastructure",
		tools: ["Read", "Write", "Bash"],
		file: "mcp-builder.md",
	},
	{
		name: "orchestrator",
		description: "Task orchestrator agent",
		category: "infrastructure",
		tools: ["Bash", "Read", "Write"],
		file: "orchestrator.md",
	},
	{
		name: "architect",
		description: "System architecture agent",
		category: "analysis",
		tools: ["Read", "Bash", "Write"],
		file: "architect.md",
	},
	{
		name: "autonomous-optimization-architect",
		description: "Autonomous optimization agent",
		category: "analysis",
		tools: ["Bash", "Read", "Write", "Edit"],
		file: "autonomous-optimization-architect.md",
	},
	{
		name: "feedback-synthesizer",
		description: "Feedback synthesis agent",
		category: "analysis",
		tools: ["Read", "Write"],
		file: "feedback-synthesizer.md",
	},
	{
		name: "knowledge-curator",
		description: "Knowledge curation agent",
		category: "analysis",
		tools: ["Read", "Write", "Bash"],
		file: "knowledge-curator.md",
	},
	{
		name: "docs-generator",
		description: "Documentation generator",
		category: "analysis",
		tools: ["Read", "Write"],
		file: "docs-generator.md",
	},
	{
		name: "debugger",
		description: "Debug specialist agent",
		category: "analysis",
		tools: ["Bash", "Read", "Write"],
		file: "debugger.md",
	},
	{
		name: "refactor-expert",
		description: "Code refactor agent",
		category: "analysis",
		tools: ["Read", "Write", "Edit"],
		file: "refactor-expert.md",
	},
	{
		name: "resilience-tester",
		description: "Resilience testing agent",
		category: "analysis",
		tools: ["Bash", "Read"],
		file: "resilience-tester.md",
	},
	{
		name: "ui-ux",
		description: "UI/UX analysis agent",
		category: "analysis",
		tools: ["Read", "Bash", "Write"],
		file: "ui-ux.md",
	},
	{
		name: "gsd-nyquist-auditor",
		description: "GSD Nyquist validation auditor",
		category: "gsd",
		tools: ["Read", "Write", "Edit", "Bash", "Glob", "Grep"],
		file: "gsd-nyquist-auditor.md",
	},
	{
		name: "gsd-ui-auditor",
		description: "GSD UI audit agent",
		category: "gsd",
		tools: ["Read", "Write", "Bash", "Grep", "Glob"],
		file: "gsd-ui-auditor.md",
	},
	{
		name: "gsd-ui-checker",
		description: "GSD UI spec checker",
		category: "gsd",
		tools: ["Read", "Bash", "Glob", "Grep"],
		file: "gsd-ui-checker.md",
	},
	{
		name: "gsd-ui-researcher",
		description: "GSD UI researcher",
		category: "gsd",
		tools: ["Read", "Write", "Bash", "Grep", "Glob", "WebSearch", "WebFetch"],
		file: "gsd-ui-researcher.md",
	},
];

// ── External Agents ───────────────────────────────────────────────────────────

const agentsExternal: ExternalAgentsResponse = {
	providers: {
		gemini: {
			available: true,
			model: "gemini-3.1-pro-preview",
			config_exists: true,
			path: "fnm/bin/gemini (v0.35.3)",
		},
		codex: {
			available: true,
			model: "gpt-5.4",
			config_exists: true,
			path: "fnm/bin/codex (v0.114)",
		},
		kimi: {
			available: true,
			model: "kimi-k2.5",
			config_exists: true,
			yolo: true,
			path: "/home/nadavcohen/.local/bin/kimi",
		},
		minimax: {
			available: true,
			model: "MiniMax-M2.7",
			config_exists: true,
			context_k: 204000,
			path: "/home/nadavcohen/.local/bin/minimax",
		},
	},
};

// ── Hydra Tasks ───────────────────────────────────────────────────────────────

const hydraTasks: HydraTask[] = [
	{
		id: "mexicani-bundle-opt-2026-03-26",
		status: "completed",
		steps: 10,
		checkpoints: 12,
		display_name: "mexicani-bundle-opt-2026-03-26",
	},
	{
		id: "sportchat-riverpod3-migration",
		status: "verified",
		steps: 8,
		checkpoints: 9,
		display_name: "sportchat-riverpod3-migration",
	},
	{
		id: "ci-standards-deploy-all-repos",
		status: "completed",
		steps: 11,
		checkpoints: 14,
		display_name: "ci-standards-deploy-all-repos",
	},
	{
		id: "hydra-v2-full-build",
		status: "verified",
		steps: 9,
		checkpoints: 10,
		display_name: "hydra-v2-full-build",
	},
	{
		id: "security-audit-all-rls",
		status: "completed",
		steps: 7,
		checkpoints: 8,
		display_name: "security-audit-all-rls",
	},
];

// ── Hydra Scores ──────────────────────────────────────────────────────────────

const hydraScores: HydraScoresResponse = {
	providers: {
		codex: {
			score: 0.692,
			successes: 8,
			failures: 3,
			total: 11,
			last_updated: "2026-03-26T08:23:04Z",
		},
		kimi: {
			score: 0.778,
			successes: 6,
			failures: 1,
			total: 7,
			last_updated: "2026-03-07T19:44:30Z",
		},
		gemini: {
			score: 0.8,
			successes: 3,
			failures: 0,
			total: 3,
			last_updated: "2026-03-02T06:46:28Z",
		},
		minimax: {
			score: 0.5,
			successes: 0,
			failures: 0,
			total: 0,
			last_updated: "2026-03-28T00:00:00Z",
		},
	},
	version: "1.1.0",
	created_at: "2026-03-02T00:00:00Z",
};

// ── Hydra Watcher ─────────────────────────────────────────────────────────────

const hydraWatcher: WatcherResponse = {
	events: [
		{
			ts: "2026-03-26T10:05:00Z",
			event: "task_completed",
			task_id: "mexicani-bundle-opt-2026-03-26",
			provider: "codex",
			rc: 0,
		},
		{
			ts: "2026-03-26T09:55:00Z",
			event: "execute_start",
			task_id: "mexicani-bundle-opt-2026-03-26",
			provider: "codex",
		},
		{
			ts: "2026-03-26T09:45:00Z",
			event: "task_queued",
			task_id: "hydra-v2-full-build",
			provider: "gemini",
		},
		{
			ts: "2026-03-26T09:30:00Z",
			event: "task_completed",
			task_id: "hydra-v2-full-build",
			provider: "gemini",
			rc: 0,
		},
		{
			ts: "2026-03-26T08:00:00Z",
			event: "watcher_start",
			message: "hydra_watcher.py started with --sqlite",
		},
	],
};

// ── Hydra Health ──────────────────────────────────────────────────────────────

const hydraHealth: HealthResponse = {
	status: "healthy",
	timestamp: "2026-03-26T10:00:00Z",
	checks: [
		{
			name: "sqlite_db",
			ok: true,
			message: "exists at ~/.claude/knowledge/hydra-state.db",
			duration_ms: 2,
		},
		{
			name: "langgraph_compile",
			ok: true,
			message: "hydra_graph.py present",
			duration_ms: 45,
		},
		{
			name: "lancedb_memory",
			ok: true,
			message: "directory present",
			duration_ms: 1,
		},
		{ name: "log_file", ok: true, message: "log dir ok", duration_ms: 1 },
		{
			name: "shell_scripts",
			ok: true,
			message: "hydra-executor.sh present",
			duration_ms: 1,
		},
	],
};

// ── Hooks ─────────────────────────────────────────────────────────────────────

const hooks: HooksResponse = {
	total: 115,
	by_event: {
		PreToolUse: 30,
		PostToolUse: 19,
		Stop: 14,
		UserPromptSubmit: 11,
		SessionStart: 12,
		PostCompact: 3,
		SubagentStop: 6,
		PostToolUseFailure: 4,
		SubagentStart: 1,
		PermissionRequest: 2,
		Notification: 1,
		ConfigChange: 1,
		WorktreeCreate: 1,
		WorktreeRemove: 1,
		TaskCompleted: 1,
		TeammateIdle: 1,
		PreCompact: 1,
		CwdChanged: 1,
	},
	recent: [
		{
			hook: "anti-premature-completion.sh",
			duration_ms: 12,
			ts: "2026-03-26T10:04:55Z",
		},
		{
			hook: "post-edit-format.sh",
			duration_ms: 45,
			ts: "2026-03-26T10:04:30Z",
		},
		{
			hook: "post-edit-typecheck.sh",
			duration_ms: 820,
			ts: "2026-03-26T10:04:10Z",
		},
		{
			hook: "prerequisite-check.sh",
			duration_ms: 8,
			ts: "2026-03-26T10:03:50Z",
		},
		{
			hook: "knowledge-capture.sh",
			duration_ms: 22,
			ts: "2026-03-26T10:03:20Z",
		},
	],
};

// ── System ────────────────────────────────────────────────────────────────────

const system: SystemResponse = {
	ram: { total_gb: 64.0, used_gb: 22.4, free_gb: 41.6, pct: 35.0 },
	swap: { total_gb: 200.0, used_gb: 1.2, pct: 0.6 },
	disk: { total_gb: 936, used_gb: 457, free_gb: 437, pct: 52.0 },
	uptime: "12d 4h 33m",
	uptime_sec: 1056780,
	orphan_count: 0,
	earlyoom: "active",
	handoffs: {
		pending: 0,
		"in-progress": 0,
		completed: 26,
		failed: 0,
		verified: 35,
	},
};

// ── Metrics ───────────────────────────────────────────────────────────────────

const metrics: MetricsResponse = {
	total_dispatches: 595,
	top_agents: [
		{ name: "code-reviewer", count: 48 },
		{ name: "test-generator", count: 42 },
		{ name: "gsd-executor", count: 38 },
		{ name: "architect", count: 27 },
		{ name: "security-auditor", count: 24 },
		{ name: "bundle-analyzer", count: 19 },
		{ name: "rtl-fixer", count: 17 },
		{ name: "migration", count: 14 },
		{ name: "devops", count: 12 },
		{ name: "autonomous-optimization", count: 11 },
	],
	top_projects: [
		{ name: "mexicani", count: 82 },
		{ name: "sportchat", count: 41 },
		{ name: "shifts", count: 38 },
		{ name: "Z", count: 31 },
		{ name: "mediflow", count: 28 },
		{ name: "hatumdigital", count: 22 },
		{ name: "brain", count: 18 },
		{ name: "nadavai", count: 12 },
	],
	provider_events: [
		{ provider: "codex", event: "success", count: 8 },
		{ provider: "codex", event: "error", count: 3 },
		{ provider: "kimi", event: "success", count: 6 },
		{ provider: "kimi", event: "error", count: 1 },
		{ provider: "gemini", event: "success", count: 3 },
		{ provider: "gemini", event: "error", count: 0 },
		{ provider: "minimax", event: "success", count: 0 },
		{ provider: "minimax", event: "error", count: 0 },
	],
};

// ── Memory ────────────────────────────────────────────────────────────────────

const memory: MemoryResponse = {
	exists: true,
	line_count: 81,
	last_modified: "2026-03-26T10:00:00Z",
	sections: [
		"User Preferences",
		"System Counts",
		"Custom Learning Pipeline",
		"Key Technical Learnings",
		"Multi-Model Dispatch",
		"GSD Configuration",
		"Infrastructure State",
		"MCP Profiles",
		"MiniMax Direct API",
		"BrowserStack",
	],
	knowledge_files: 102,
	rules_files: 12,
	rules_count: 12,
};

// ── Rules ─────────────────────────────────────────────────────────────────────

const rules: RuleInfo[] = [
	{
		name: "auto-learned-rules.md",
		path: "rules/quality/auto-learned-rules.md",
		category: "quality",
		size_kb: 45.8,
		last_modified: "2026-03-26T10:00:00Z",
	},
	{
		name: "auto-learned-rules-archive.md",
		path: "rules/quality/auto-learned-rules-archive.md",
		category: "quality",
		size_kb: 20.1,
		last_modified: "2026-03-25T20:00:00Z",
	},
	{
		name: "code-quality.md",
		path: "rules/quality/code-quality.md",
		category: "quality",
		size_kb: 2.0,
		last_modified: "2026-03-20T00:00:00Z",
	},
	{
		name: "past-mistakes.md",
		path: "rules/quality/past-mistakes.md",
		category: "quality",
		size_kb: 34.2,
		last_modified: "2026-03-26T08:00:00Z",
	},
	{
		name: "rtl-i18n.md",
		path: "rules/quality/rtl-i18n.md",
		category: "quality",
		size_kb: 1.0,
		last_modified: "2026-03-20T00:00:00Z",
	},
	{
		name: "verification.md",
		path: "rules/quality/verification.md",
		category: "quality",
		size_kb: 3.2,
		last_modified: "2026-03-20T00:00:00Z",
	},
	{
		name: "security.md",
		path: "rules/security/security.md",
		category: "security",
		size_kb: 3.9,
		last_modified: "2026-03-25T00:00:00Z",
	},
	{
		name: "ai-security.md",
		path: "rules/security/ai-security.md",
		category: "security",
		size_kb: 3.5,
		last_modified: "2026-03-25T00:00:00Z",
	},
	{
		name: "audit-gates.md",
		path: "rules/verification/audit-gates.md",
		category: "verification",
		size_kb: 2.0,
		last_modified: "2026-03-20T00:00:00Z",
	},
	{
		name: "hydra-v2-rules.md",
		path: "rules/infra/hydra-v2-rules.md",
		category: "infra",
		size_kb: 21.5,
		last_modified: "2026-03-26T10:00:00Z",
	},
	{
		name: "ops-rules.md",
		path: "rules/infra/ops-rules.md",
		category: "infra",
		size_kb: 32.5,
		last_modified: "2026-03-26T08:00:00Z",
	},
	{
		name: "stack-rules.md",
		path: "rules/infra/stack-rules.md",
		category: "infra",
		size_kb: 9.8,
		last_modified: "2026-03-25T00:00:00Z",
	},
];

// ── Skills ────────────────────────────────────────────────────────────────────

const skills: SkillsResponse = {
	total: 237,
	categories: {
		apex: 28,
		conductor: 18,
		uipro: 15,
		skill: 14,
		hydra: 12,
		ui: 12,
		agent: 11,
		ai: 10,
		flutter: 9,
		mobile: 8,
		code: 12,
		test: 10,
		security: 10,
		devops: 9,
		review: 8,
		frontend: 7,
		backend: 6,
		docs: 5,
		plannotator: 3,
		recall: 3,
	},
	plugins_count: 26,
	plugins: {},
};

// ── MCP ───────────────────────────────────────────────────────────────────────

const mcp: McpResponse = {
	servers: [
		{
			name: "context7",
			source: "plugin",
			enabled: true,
			transport: "stdio",
		},
		{
			name: "github",
			source: "plugin",
			enabled: true,
			transport: "stdio",
		},
		{
			name: "playwright",
			source: "plugin",
			enabled: true,
			transport: "stdio",
		},
		{
			name: "supabase",
			source: "plugin",
			enabled: true,
			transport: "stdio",
		},
		{
			name: "claude-mem",
			source: "plugin",
			enabled: true,
			transport: "stdio",
		},
		{
			name: "browserstack",
			source: "~/.mcp.json",
			enabled: true,
			transport: "stdio",
		},
		{
			name: "minimax",
			source: "~/.mcp.json",
			enabled: true,
			transport: "stdio",
		},
		{
			name: "telegram",
			source: "plugin",
			enabled: true,
			transport: "stdio",
		},
		{
			name: "firebase",
			source: "plugin",
			enabled: true,
			transport: "stdio",
		},
		{
			name: "serena",
			source: "plugin",
			enabled: true,
			transport: "stdio",
		},
		{
			name: "chrome-devtools",
			source: "settings.json",
			enabled: true,
			transport: "stdio",
		},
		{
			name: "chroma",
			source: "plugin",
			enabled: false,
			transport: "stdio",
		},
	],
	total: 16,
	enabled: 14,
	disabled: 2,
	plugins: {},
	plugins_count: 26,
};

// ── OpenClaw ──────────────────────────────────────────────────────────────────

const openclaw: OpenclawResponse = {
	skills: 195,
	version: "v2026.4.9",
};

const openclawDetails: OpenclawDetailsResponse = {
	skills: [
		{
			name: "code-reviewer",
			slug: "code-reviewer",
			description: "L10+ 16-dimension code review",
			version: "3.2.0",
			tags: ["quality", "review"],
			file: "SKILL.md",
			size_kb: 18.4,
		},
		{
			name: "adversarial-review",
			slug: "adversarial-review",
			description: "Adversarial security review",
			version: "2.1.0",
			tags: ["security", "review"],
			file: "SKILL.md",
			size_kb: 12.2,
		},
		{
			name: "reality-checker",
			slug: "reality-checker",
			description: "Reality check — verify claims",
			version: "1.8.0",
			tags: ["quality"],
			file: "SKILL.md",
			size_kb: 8.6,
		},
		{
			name: "edge-case-hunter",
			slug: "edge-case-hunter",
			description: "Hunt edge cases in code",
			version: "1.5.0",
			tags: ["quality", "testing"],
			file: "SKILL.md",
			size_kb: 9.1,
		},
		{
			name: "brainstorming",
			slug: "brainstorming",
			description: "Structured brainstorming session",
			version: "2.0.0",
			tags: ["ideation"],
			file: "SKILL.md",
			size_kb: 11.3,
		},
		{
			name: "implement-playground",
			slug: "implement-playground",
			description: "1:1 playground implementation",
			version: "1.4.0",
			tags: ["ui", "frontend"],
			file: "SKILL.md",
			size_kb: 14.8,
		},
		{
			name: "ui-shadcn",
			slug: "ui-shadcn",
			description: "shadcn/ui component generation",
			version: "1.2.0",
			tags: ["ui"],
			file: "SKILL.md",
			size_kb: 7.2,
		},
		{
			name: "security-rules",
			slug: "security-rules",
			description: "Security rules on-demand",
			version: "2.3.0",
			tags: ["security"],
			file: "SKILL.md",
			size_kb: 6.5,
		},
		{
			name: "flutter-rules",
			slug: "flutter-rules",
			description: "Flutter 2026 rules on-demand",
			version: "1.9.0",
			tags: ["flutter", "mobile"],
			file: "SKILL.md",
			size_kb: 5.8,
		},
		{
			name: "testing-rules",
			slug: "testing-rules",
			description: "Testing rules on-demand",
			version: "1.6.0",
			tags: ["testing"],
			file: "SKILL.md",
			size_kb: 5.3,
		},
	],
	skills_count: 195,
	subagents: [
		{
			name: "gsd-executor",
			path: "/home/nadavcohen/.openclaw/subagents/gsd-executor",
		},
		{
			name: "gsd-verifier",
			path: "/home/nadavcohen/.openclaw/subagents/gsd-verifier",
		},
		{
			name: "code-reviewer",
			path: "/home/nadavcohen/.openclaw/subagents/code-reviewer",
		},
		{
			name: "rtl-fixer",
			path: "/home/nadavcohen/.openclaw/subagents/rtl-fixer",
		},
	],
	subagents_count: 4,
	version: "v2026.3.22",
	path: "/home/nadavcohen/.openclaw",
};

// ── Sync / Lenovo ────────────────────────────────────────────────────────────────

const sync: SyncResponse = {
	synced: true,
	last_sync: "2026-03-26T08:00:00Z",
	drift: [],
};

const lenovoStatus: LenovoStatusResponse = {
	reachable: true,
	hostname: "pop-os",
	load_avg: [1.2, 1.5, 1.8],
};

const syncStatus: SyncStatusResponse = {
	status: "in_sync",
	last_push: "2026-03-26T08:00:00Z",
	last_pull: "2026-03-26T07:55:00Z",
};

const crossSync: CrossSyncResponse = {
	pop_os: {
		gemini: {
			rules_synced: true,
			file_count: 8,
			rules_dir: "/home/nadavcohen/.gemini/rules",
		},
		codex: {
			rules_synced: true,
			file_count: 8,
			rules_dir: "/home/nadavcohen/.codex/rules",
		},
		kimi: {
			rules_synced: true,
			file_count: 6,
			rules_dir: "/home/nadavcohen/.kimi/rules",
		},
		minimax: {
			rules_synced: true,
			file_count: 5,
			rules_dir: "/home/nadavcohen/.minimax/rules",
		},
	},
	lenovo: {
		gemini: {
			rules_synced: true,
			file_count: 8,
			rules_dir: "/home/nadavcohen/.gemini/rules",
		},
		codex: {
			rules_synced: true,
			file_count: 8,
			rules_dir: "/home/nadavcohen/.codex/rules",
		},
		kimi: {
			rules_synced: false,
			file_count: 0,
			rules_dir: "/home/nadavcohen/.kimi/rules",
		},
		minimax: {
			rules_synced: false,
			file_count: 0,
			rules_dir: "/home/nadavcohen/.minimax/rules",
		},
	},
	diff: ["MSI: kimi rules not synced", "MSI: minimax rules not synced"],
};

const watcherAll: WatcherResponse = {
	events: [
		{
			ts: "2026-03-26T10:05:00Z",
			event: "task_completed",
			task_id: "mexicani-bundle-opt-2026-03-26",
			provider: "codex",
			rc: 0,
		},
		{
			ts: "2026-03-26T10:04:55Z",
			event: "hook_fire",
			message: "anti-premature-completion.sh",
		},
		{
			ts: "2026-03-26T09:55:00Z",
			event: "execute_start",
			task_id: "mexicani-bundle-opt-2026-03-26",
			provider: "codex",
		},
		{
			ts: "2026-03-26T09:45:00Z",
			event: "dispatch",
			task_id: "hydra-v2-full-build",
			provider: "gemini",
		},
		{
			ts: "2026-03-26T09:30:00Z",
			event: "task_completed",
			task_id: "hydra-v2-full-build",
			provider: "gemini",
			rc: 0,
		},
		{
			ts: "2026-03-26T09:20:00Z",
			event: "mcp_call",
			message: "context7: resolve-library-id",
		},
		{
			ts: "2026-03-26T08:00:00Z",
			event: "watcher_start",
			message: "hydra_watcher.py started with --sqlite",
		},
	],
};

// ── Notifications ─────────────────────────────────────────────────────────────

const notificationsConfig: NotificationConfig = {
	token_set: true,
	chat_id_set: true,
	rules: {
		task_failed: true,
		health_critical: true,
		ram_high: true,
		lenovo_unreachable: true,
	},
};

const notificationsLog: NotificationEvent[] = [
	{
		ts: "2026-03-26T09:00:00Z",
		event: "test",
		message: "בדיקת התראות עבדה! המערכת מחוברת.",
		sent: true,
	},
	{
		ts: "2026-03-25T22:30:00Z",
		event: "task_failed",
		message: "⚠️ משימה נכשלה: kimi-wave-12 (ספק: kimi)",
		sent: true,
	},
	{
		ts: "2026-03-25T18:00:00Z",
		event: "ram_high",
		message: "⚠️ RAM גבוה: 91%",
		sent: true,
	},
	{
		ts: "2026-03-24T10:00:00Z",
		event: "health_critical",
		message: "🔴 בדיקת בריאות קריטית: sqlite_db",
		sent: false,
	},
];

// ── CI Status ─────────────────────────────────────────────────────────────────

const ciStatus: CiStatusResponse = {
	repos: [
		{
			name: "Mexicani",
			full_name: "Nadav011/Mexicani",
			runs: [
				{
					status: "completed",
					conclusion: "success",
					name: "CI",
					createdAt: "2026-03-26T09:00:00Z",
					headBranch: "main",
					url: "https://github.com/Nadav011/Mexicani/actions/runs/1",
				},
			],
		},
		{
			name: "mexicani-shifts",
			full_name: "Nadav011/mexicani-shifts",
			runs: [
				{
					status: "completed",
					conclusion: "success",
					name: "CI",
					createdAt: "2026-03-26T08:00:00Z",
					headBranch: "main",
					url: "https://github.com/Nadav011/mexicani-shifts/actions/runs/2",
				},
			],
		},
		{
			name: "Z",
			full_name: "Nadav011/Z",
			runs: [
				{
					status: "completed",
					conclusion: "success",
					name: "CI",
					createdAt: "2026-03-25T22:00:00Z",
					headBranch: "main",
					url: "https://github.com/Nadav011/Z/actions/runs/3",
				},
			],
		},
		{
			name: "hatumdigital",
			full_name: "Nadav011/hatumdigital",
			runs: [
				{
					status: "completed",
					conclusion: "success",
					name: "CI",
					createdAt: "2026-03-25T20:00:00Z",
					headBranch: "main",
					url: "https://github.com/Nadav011/hatumdigital/actions/runs/4",
				},
			],
		},
		{
			name: "brain",
			full_name: "Nadav011/brain",
			runs: [
				{
					status: "completed",
					conclusion: "success",
					name: "CI",
					createdAt: "2026-03-25T18:00:00Z",
					headBranch: "master",
					url: "https://github.com/Nadav011/brain/actions/runs/5",
				},
			],
		},
		{
			name: "vibechat",
			full_name: "Nadav011/vibechat",
			runs: [
				{
					status: "completed",
					conclusion: "failure",
					name: "CI",
					createdAt: "2026-03-25T16:00:00Z",
					headBranch: "main",
					url: "https://github.com/Nadav011/vibechat/actions/runs/6",
				},
			],
		},
		{
			name: "sportchat-ultimate",
			full_name: "Nadav011/sportchat-ultimate",
			runs: [
				{
					status: "completed",
					conclusion: "success",
					name: "CI",
					createdAt: "2026-03-25T14:00:00Z",
					headBranch: "main",
					url: "https://github.com/Nadav011/sportchat-ultimate/actions/runs/7",
				},
			],
		},
		{
			name: "nadavai",
			full_name: "Nadav011/nadavai",
			runs: [
				{
					status: "completed",
					conclusion: "success",
					name: "CI",
					createdAt: "2026-03-25T12:00:00Z",
					headBranch: "main",
					url: "https://github.com/Nadav011/nadavai/actions/runs/8",
				},
			],
		},
		{
			name: "signature-pro",
			full_name: "Nadav011/signature-pro",
			runs: [
				{
					status: "completed",
					conclusion: "success",
					name: "CI",
					createdAt: "2026-03-25T10:00:00Z",
					headBranch: "main",
					url: "https://github.com/Nadav011/signature-pro/actions/runs/9",
				},
			],
		},
		{
			name: "chance-pro",
			full_name: "Nadav011/chance-pro",
			runs: [
				{
					status: "completed",
					conclusion: "success",
					name: "CI",
					createdAt: "2026-03-25T08:00:00Z",
					headBranch: "main",
					url: "https://github.com/Nadav011/chance-pro/actions/runs/10",
				},
			],
		},
		{
			name: "design-system",
			full_name: "Nadav011/design-system",
			runs: [
				{
					status: "completed",
					conclusion: "success",
					name: "CI",
					createdAt: "2026-03-24T22:00:00Z",
					headBranch: "main",
					url: "https://github.com/Nadav011/design-system/actions/runs/11",
				},
			],
		},
		{ name: "my-video", full_name: "Nadav011/my-video", runs: [] },
		{
			name: "israeli-finance-app",
			full_name: "Nadav011/israeli-finance-app",
			runs: [
				{
					status: "completed",
					conclusion: "success",
					name: "CI",
					createdAt: "2026-03-24T18:00:00Z",
					headBranch: "master",
					url: "https://github.com/Nadav011/israeli-finance-app/actions/runs/12",
				},
			],
		},
	],
	updated_at: "2026-03-26T10:00:00Z",
};

const ciSummary: CiSummaryResponse = {
	total: 13,
	passing: 11,
	failing: 1,
	unknown: 1,
	last_check: "2026-03-26T10:00:00Z",
};

const ciTemplates: CiTemplatesResponse = {
	templates: [
		{
			file: "ci-vite-react.yml",
			name: "CI — Vite + React",
			size_kb: 8.4,
			lines: 210,
		},
		{ file: "ci-nextjs.yml", name: "CI — Next.js", size_kb: 7.9, lines: 195 },
		{ file: "ci-flutter.yml", name: "CI — Flutter", size_kb: 6.2, lines: 158 },
		{
			file: "deploy-cf-pages.yml",
			name: "Deploy — CF Pages",
			size_kb: 3.1,
			lines: 78,
		},
		{
			file: "deploy-netlify.yml",
			name: "Deploy — Netlify",
			size_kb: 2.8,
			lines: 72,
		},
		{ file: "bundle-check.yml", name: "Bundle Check", size_kb: 2.2, lines: 55 },
		{
			file: "lighthouse-ci.yml",
			name: "Lighthouse CI",
			size_kb: 2.5,
			lines: 62,
		},
		{
			file: "trivy-autofix.yml",
			name: "Trivy CVE Auto-fix",
			size_kb: 3.4,
			lines: 85,
		},
	],
	count: 8,
	path: "/home/nadavcohen/ci-standards",
};

const ciDeep: CiDeepResponse = {
	pipeline: [
		{ name: "install", jobs: ["pnpm install --frozen-lockfile"] },
		{
			name: "quality",
			jobs: [
				"typecheck",
				"lint (Biome 2.4.4)",
				"semgrep",
				"trivy",
				"gitleaks",
				"socket-ci",
			],
			duration_estimate: "2-4 min",
		},
		{
			name: "test",
			jobs: [
				"vitest --maxWorkers=2 --shard=1/4",
				"vitest --maxWorkers=2 --shard=2/4",
				"vitest --maxWorkers=2 --shard=3/4",
				"vitest --maxWorkers=2 --shard=4/4",
			],
			duration_estimate: "3-8 min",
		},
		{ name: "lighthouse", jobs: ["lhci autorun"] },
		{ name: "build", jobs: ["pnpm build"] },
		{
			name: "deploy",
			jobs: ["CF Pages / Netlify deploy"],
			duration_estimate: "1-3 min",
		},
	],
	tools: [
		{
			name: "Biome",
			version: "2.4.4",
			category: "quality",
			command: "biome check . --apply",
			purpose: "Linting + formatting",
			blocking: true,
			docs_url: "https://biomejs.dev",
		},
		{
			name: "Vitest",
			version: "4.0.18",
			category: "testing",
			command: "vitest --maxWorkers=2",
			purpose: "Unit + integration tests",
			blocking: true,
		},
		{
			name: "Playwright",
			version: "1.58.2",
			category: "testing",
			command: "playwright test",
			purpose: "E2E browser tests",
			blocking: true,
		},
		{
			name: "trivy",
			version: "0.69.3",
			category: "security",
			command: "trivy fs . --severity HIGH,CRITICAL",
			purpose: "CVE scanning",
			blocking: true,
			docs_url: "https://aquasecurity.github.io/trivy",
		},
		{
			name: "semgrep",
			version: "1.155.0",
			category: "security",
			command: "semgrep scan . --config=auto",
			purpose: "SAST / OWASP scanning",
			blocking: true,
		},
		{
			name: "gitleaks",
			version: "latest",
			category: "security",
			command: ".github/workflows (auto)",
			purpose: "Secret detection",
			blocking: true,
		},
		{
			name: "socket",
			version: "1.1.73",
			category: "security",
			command: "socket npm install <pkg>",
			purpose: "Supply chain security",
			blocking: false,
		},
		{
			name: "Lighthouse CI",
			version: "0.15.1",
			category: "perf",
			command: "lhci autorun",
			purpose: "Performance audits",
			blocking: false,
		},
		{
			name: "k6",
			version: "1.6.1",
			category: "perf",
			command: "k6 run tests/load/test.js",
			purpose: "Load testing",
			blocking: false,
		},
		{
			name: "git-cliff",
			version: "2.12.0",
			category: "dev",
			command: "git-cliff -o CHANGELOG.md",
			purpose: "Changelog generation",
			blocking: false,
		},
		{
			name: "type-coverage",
			version: "2.29.7",
			category: "quality",
			command: "type-coverage --at-least 90 --detail",
			purpose: "TypeScript any% detection",
			blocking: false,
		},
		{
			name: "knip",
			version: "5.86.0",
			category: "quality",
			command: "knip",
			purpose: "Dead code detection",
			blocking: false,
		},
		{
			name: "act",
			version: "0.2.84",
			category: "dev",
			command: "act push",
			purpose: "Local CI debug",
			blocking: false,
		},
		{
			name: "hurl",
			version: "7.1.0",
			category: "testing",
			command: "hurl tests/api/",
			purpose: "API testing",
			blocking: false,
		},
	],
	reusable_workflows: {
		repo: "Nadav011/ci-standards",
		workflows: [
			{
				file: "ci-vite-react.yml",
				name: "CI — Vite + React",
				description: "Full CI for Vite + React projects",
				triggers: ["push", "pull_request"],
				jobs: [
					"typecheck",
					"lint",
					"semgrep",
					"trivy",
					"gitleaks",
					"test",
					"build",
				],
				secrets_required: ["SUPABASE_URL", "SUPABASE_ANON_KEY"],
				repos_using: 7,
			},
			{
				file: "ci-nextjs.yml",
				name: "CI — Next.js",
				description: "Full CI for Next.js projects",
				triggers: ["push", "pull_request"],
				jobs: [
					"typecheck",
					"lint",
					"semgrep",
					"trivy",
					"gitleaks",
					"test",
					"build",
				],
				secrets_required: ["SUPABASE_URL", "SUPABASE_ANON_KEY"],
				repos_using: 3,
			},
			{
				file: "ci-flutter.yml",
				name: "CI — Flutter",
				description: "CI for Flutter/Dart projects",
				triggers: ["push", "pull_request"],
				jobs: ["analyze", "test", "build"],
				secrets_required: ["FIREBASE_CONFIG"],
				repos_using: 1,
			},
		],
	},
	github_apps: [
		{
			name: "Renovate",
			purpose: "Weekly dependency update PRs",
			installed_on: [
				"Mexicani",
				"mexicani-shifts",
				"Z",
				"hatumdigital",
				"brain",
				"vibechat",
				"sportchat-ultimate",
				"nadavai",
				"signature-pro",
				"chance-pro",
				"design-system",
				"my-video",
				"israeli-finance-app",
			],
			auto_pr: true,
			webhook_events: ["push"],
		},
		{
			name: "Socket.dev",
			purpose: "Supply chain security checks",
			installed_on: [
				"Mexicani",
				"mexicani-shifts",
				"Z",
				"hatumdigital",
				"brain",
				"vibechat",
				"sportchat-ultimate",
				"nadavai",
				"signature-pro",
				"chance-pro",
				"design-system",
				"my-video",
				"israeli-finance-app",
			],
			auto_pr: false,
			webhook_events: ["pull_request"],
		},
		{
			name: "CodeRabbit",
			purpose: "AI automated code review",
			installed_on: [
				"Mexicani",
				"mexicani-shifts",
				"Z",
				"hatumdigital",
				"brain",
				"vibechat",
				"sportchat-ultimate",
				"nadavai",
				"signature-pro",
				"chance-pro",
				"design-system",
				"my-video",
				"israeli-finance-app",
			],
			auto_pr: false,
			webhook_events: ["pull_request"],
		},
	],
	security_gates: [
		{
			name: "harden-runner",
			tool: "step-security/harden-runner@v2.16.0",
			blocking: true,
			severity_threshold: "critical",
			notes: "CVE-2026-25598 + GHSA-g699 patched — pin to v2.16.0",
		},
		{
			name: "trivy-action",
			tool: "aquasecurity/trivy-action@<SHA>",
			blocking: true,
			severity_threshold: "HIGH",
			notes: "SHA-pinned — 75/76 tags compromised March 2026",
		},
		{
			name: "attest-build-provenance",
			tool: "actions/attest-build-provenance@v4",
			blocking: false,
			notes: "SLSA v4 provenance",
		},
		{
			name: "cancel-in-progress",
			tool: "concurrency.cancel-in-progress",
			blocking: false,
			notes: "true for CI, false for deploy",
		},
		{
			name: "runs-on",
			tool: "[self-hosted, linux, x64, pop-os]",
			blocking: true,
			notes: "NEVER ubuntu-latest",
		},
		{
			name: "needs: ci-gate",
			tool: "deploy.yml needs: [ci-gate]",
			blocking: true,
			notes: "deploy must depend on ci-gate",
		},
	],
	runners: [
		{
			label: "[self-hosted, linux, x64, pop-os]",
			machine: "Lenovo (Pop!_OS)",
			ip: "100.82.33.122",
			cores: 24,
			ram_gb: 64,
			count: 17,
			status: "online",
			total: 22,
		},
		{
			label: "[self-hosted, linux, x64, msi]",
			machine: "MSI",
			ip: "100.87.247.87",
			cores: 12,
			ram_gb: 64,
			count: 5,
			status: "online",
		},
	],
	per_project: [
		{
			name: "Mexicani",
			stack: "Vite+React",
			machine: "Lenovo",
			has_ci: true,
			test_shards: 4,
			bundle_check: true,
			security_scan: true,
			deploy_gate: true,
			branch: "main",
		},
		{
			name: "Chance Pro",
			stack: "Python",
			machine: "Lenovo",
			has_ci: true,
			test_shards: 1,
			bundle_check: false,
			security_scan: true,
			deploy_gate: true,
			branch: "main",
		},
		{
			name: "MediFlow",
			stack: "Next.js",
			machine: "Lenovo",
			has_ci: true,
			test_shards: 1,
			bundle_check: true,
			security_scan: true,
			deploy_gate: false,
			branch: "main",
		},
		{
			name: "NadavAI",
			stack: "Next.js",
			machine: "Lenovo",
			has_ci: true,
			test_shards: 1,
			bundle_check: true,
			security_scan: true,
			deploy_gate: true,
			branch: "main",
		},
		{
			name: "Z (Cash)",
			stack: "Vite+React+npm",
			machine: "MSI",
			has_ci: true,
			test_shards: 4,
			bundle_check: true,
			security_scan: true,
			deploy_gate: true,
			branch: "main",
		},
		{
			name: "Cash",
			stack: "Vite+React",
			machine: "MSI",
			has_ci: true,
			test_shards: 1,
			bundle_check: true,
			security_scan: true,
			deploy_gate: true,
			branch: "main",
		},
		{
			name: "Shifts",
			stack: "Vite+React",
			machine: "MSI",
			has_ci: true,
			test_shards: 4,
			bundle_check: true,
			security_scan: true,
			deploy_gate: true,
			branch: "main",
		},
		{
			name: "HatumDigital",
			stack: "Vite+Capacitor",
			machine: "MSI",
			has_ci: true,
			test_shards: 4,
			bundle_check: true,
			security_scan: true,
			deploy_gate: true,
			branch: "main",
		},
		{
			name: "Brain",
			stack: "Vite+React",
			machine: "MSI",
			has_ci: true,
			test_shards: 4,
			bundle_check: true,
			security_scan: true,
			deploy_gate: true,
			branch: "master",
		},
		{
			name: "SportChat",
			stack: "Flutter",
			machine: "MSI",
			has_ci: true,
			test_shards: 1,
			bundle_check: false,
			security_scan: false,
			deploy_gate: false,
			branch: "main",
		},
		{
			name: "VibChat",
			stack: "Next.js+Convex",
			machine: "MSI",
			has_ci: true,
			test_shards: 1,
			bundle_check: true,
			security_scan: true,
			deploy_gate: true,
			branch: "main",
		},
		{
			name: "Design System",
			stack: "Node ESM",
			machine: "Lenovo",
			has_ci: true,
			test_shards: 1,
			bundle_check: false,
			security_scan: true,
			deploy_gate: false,
			branch: "main",
		},
		{
			name: "My Video",
			stack: "Remotion",
			machine: "Lenovo",
			has_ci: false,
			test_shards: 0,
			bundle_check: false,
			security_scan: false,
			deploy_gate: false,
			branch: "master",
		},
		{
			name: "Signature Pro",
			stack: "Vite+React",
			machine: "Lenovo",
			has_ci: true,
			test_shards: 1,
			bundle_check: true,
			security_scan: true,
			deploy_gate: true,
			branch: "main",
		},
	],
	stats: {
		total_repos: 18,
		repos_with_ci: 14,
		total_workflow_files: 196,
		total_tools: 14,
		total_security_gates: 6,
		total_runners: 22,
		total_reusable_workflows: 3,
		github_apps: 3,
		projects_with_ci: 13,
		projects_total: 18,
	},
};

// ── Deploys Status ────────────────────────────────────────────────────────────

const deploysStatus: DeploysStatusResponse = {
	sites: [
		{
			name: "mexicani",
			url: "https://mexicani.pages.dev",
			platform: "cloudflare",
			status: "up",
			http_status: 200,
			response_ms: 142,
			checked_at: "2026-03-26T10:00:00Z",
			error: null,
		},
		{
			name: "chance-pro",
			url: "https://chance-pro.pages.dev",
			platform: "cloudflare",
			status: "up",
			http_status: 200,
			response_ms: 138,
			checked_at: "2026-03-26T10:00:00Z",
			error: null,
		},
		{
			name: "nadavai",
			url: "https://nadavai-portfolio.netlify.app",
			platform: "netlify",
			status: "up",
			http_status: 200,
			response_ms: 155,
			checked_at: "2026-03-26T10:00:00Z",
			error: null,
		},
		{
			name: "shifts",
			url: "https://shifts-8ft.pages.dev",
			platform: "cloudflare",
			status: "up",
			http_status: 200,
			response_ms: 148,
			checked_at: "2026-03-26T10:00:00Z",
			error: null,
		},
		{
			name: "hatumdigital",
			url: "https://hatumdigital.pages.dev",
			platform: "cloudflare",
			status: "up",
			http_status: 200,
			response_ms: 161,
			checked_at: "2026-03-26T10:00:00Z",
			error: null,
		},
		{
			name: "brain",
			url: "https://brain-3qu.pages.dev",
			platform: "cloudflare",
			status: "up",
			http_status: 200,
			response_ms: 133,
			checked_at: "2026-03-26T10:00:00Z",
			error: null,
		},
		{
			name: "cash",
			url: "https://z-cash.pages.dev",
			platform: "cloudflare",
			status: "up",
			http_status: 200,
			response_ms: 145,
			checked_at: "2026-03-26T10:00:00Z",
			error: null,
		},
		{
			name: "signature-pro",
			url: "https://signature-pro.pages.dev",
			platform: "cloudflare",
			status: "up",
			http_status: 200,
			response_ms: 139,
			checked_at: "2026-03-26T10:00:00Z",
			error: null,
		},
		{
			name: "mediflow",
			url: "https://mediflow-nadav.netlify.app",
			platform: "netlify",
			status: "up",
			http_status: 200,
			response_ms: 210,
			checked_at: "2026-03-26T10:00:00Z",
			error: null,
		},
		{
			name: "apex-dashboard",
			url: "https://apex-dashboard-2z6.pages.dev",
			platform: "cloudflare",
			status: "up",
			http_status: 200,
			response_ms: 128,
			checked_at: "2026-03-26T10:00:00Z",
			error: null,
		},
		{
			name: "vibechat",
			url: "https://vibechat-app.netlify.app",
			platform: "netlify",
			status: "up",
			http_status: 200,
			response_ms: 162,
			checked_at: "2026-03-26T10:00:00Z",
			error: null,
		},
	],
	total: 11,
	up_count: 11,
	down_count: 0,
	checked_at: "2026-03-26T10:00:00Z",
};

// ── Projects ──────────────────────────────────────────────────────────────────

const projects: ProjectsResponse = {
	projects: [
		{
			name: "mexicani",
			display_name: "Mexicani",
			path: "~/Desktop/mexicani",
			machine: "Lenovo",
			stack: [
				"React 19.2",
				"Vite 7.3",
				"Supabase 2.97",
				"TypeScript 5.9",
				"Tailwind 4.2",
				"TanStack Query 5.90",
				"Capacitor 8.1",
				"Biome 2.4",
				"Zod 4.3",
				"Motion 12",
				"Recharts",
				"Sentry 10",
			],
			github_repo: "Nadav011/Mexicani",
			github_url: "https://github.com/Nadav011/Mexicani",
			domain: "mexicani.pages.dev",
			deploy_platform: "Cloudflare Pages",
			status: "active",
			description_he:
				"מערכת SaaS לניהול רשת מסעדות מקסיקני — 149 עמודים, 2,888 קומפוננטות, 115 טבלאות",
			description_en:
				"Enterprise SaaS franchise management for Mexicani restaurant chain.",
			default_branch: "main",
			package_manager: "pnpm",
			ci_workflows: [
				"ci.yml",
				"deploy.yml",
				"bundle-check.yml",
				"lighthouse-ci.yml",
				"trivy-autofix.yml",
				"e2e-tests.yml",
			],
			features: [
				"PWA",
				"RTL Hebrew",
				"Offline",
				"Push Notifications",
				"Supabase RLS",
				"Capacitor iOS",
				"i18n",
				"Multi-tenant",
				"39 Edge Functions",
				"228 Migrations",
			],
			testing: {
				framework: "Vitest 4",
				e2e: "Playwright 1.58",
				mutation: "Stryker",
				coverage_target: 80,
			},
			bundle_limit_kb: 450,
			security: {
				rls: true,
				csp: true,
				trivy: true,
				semgrep: true,
				gitleaks: true,
			},
			connections: [
				"Supabase Frankfurt (nqrcyhdtngiwebmqzfpr)",
				"Cloudflare Pages",
				"Telegram",
				"Sentry 10",
				"Capacitor",
			],
			supabase_project: "nqrcyhdtngiwebmqzfpr",
			related_projects: ["shifts", "MEX"],
			notes:
				"flagship. branch_id on every query. 228 migrations, 39 Edge Functions.",
			scale: {
				pages: 149,
				components: 2888,
				hooks: 521,
				lib: 519,
				tables: 115,
				migrations: 228,
				edge_functions: 39,
			},
			last_commit: {
				sha: "a1b2c3d",
				message: "chore: bundle optimization",
				date: "2026-03-26T09:00:00Z",
			},
		},
		{
			name: "chance-pro",
			display_name: "Chance Pro",
			path: "~/Desktop/chance-pro",
			machine: "Lenovo",
			stack: [
				"Python 3.10+",
				"NumPy >=2.4",
				"SciPy >=1.17",
				"SQLite",
				"Static HTML",
			],
			github_repo: "Nadav011/chance-pro",
			github_url: "https://github.com/Nadav011/chance-pro",
			domain: "chance-pro.pages.dev",
			deploy_platform: "Cloudflare Pages",
			status: "active",
			description_he:
				"לוח בקרה סטטיסטי לפאיס צ'אנס — 49,533+ הגרלות, 31 אלגוריתמים, 5 משחקים",
			description_en:
				"Advanced statistical dashboard for Israeli Pais Chance lottery. 49,533+ draws, 31 algorithms.",
			default_branch: "main",
			package_manager: "pip",
			ci_workflows: ["ci.yml", "deploy.yml", "trivy-autofix.yml"],
			features: [
				"Bayesian Statistics",
				"Monte Carlo",
				"CUSUM",
				"Entropy Analysis",
				"5 Games",
				"49,533+ Draws",
				"Dark Mode HTML",
			],
			testing: {
				framework: "pytest",
				e2e: undefined,
				mutation: "mutmut",
				coverage_target: 70,
			},
			bundle_limit_kb: 0,
			security: {
				rls: false,
				csp: false,
				trivy: true,
				semgrep: true,
				gitleaks: true,
			},
			connections: ["SQLite local", "Cloudflare Pages"],
			supabase_project: undefined,
			related_projects: [],
			notes:
				"MC null distribution — full N always. 31 algorithms across 5 lottery games.",
			scale: {
				pages: undefined,
				components: undefined,
				hooks: undefined,
				lib: undefined,
				tables: undefined,
				migrations: undefined,
				edge_functions: undefined,
			},
			last_commit: {
				sha: "b2c3d4e",
				message: "feat: add entropy analysis for Pais Chance",
				date: "2026-03-20T10:00:00Z",
			},
		},
		{
			name: "mediflow",
			display_name: "MediFlow",
			path: "~/Desktop/mediflow",
			machine: "Lenovo",
			stack: [
				"Next.js 16.1",
				"React Compiler",
				"Supabase SSR",
				"CipherStash Protect",
				"TanStack Query",
				"Zod 4",
				"Tailwind 4.x",
				"Pino",
				"Sentry",
				"Biome 2.x",
			],
			github_repo: "",
			github_url: "",
			domain: "mediflow-nadav.netlify.app",
			deploy_platform: "Netlify",
			status: "development",
			description_he:
				"פלטפורמה רפואית ישראלית — ISO 27001/27799, תיקון 13, הצפנת שדות, גישת חירום",
			description_en:
				"Israeli Medical Platform — ISO 27001/27799 + Amendment 13. Medical records with break-the-glass emergency access.",
			default_branch: "main",
			package_manager: "pnpm",
			ci_workflows: ["ci.yml", "deploy.yml", "trivy-autofix.yml"],
			features: [
				"ISO 27001/27799",
				"Amendment 13",
				"Field-level Encryption",
				"Break-the-glass Access",
				"RTL Hebrew",
				"Supabase SSR",
			],
			testing: {
				framework: "Vitest 4",
				e2e: "Playwright 1.58",
				mutation: undefined,
				coverage_target: 80,
			},
			bundle_limit_kb: 300,
			security: {
				rls: true,
				csp: true,
				trivy: true,
				semgrep: true,
				gitleaks: true,
			},
			connections: [
				"Supabase Frankfurt (placeholder)",
				"Netlify",
				"Sentry",
				"CipherStash",
			],
			supabase_project: "nqrcyhdtngiwebmqzfpr",
			related_projects: [],
			notes:
				"Early stage. Netlify deploy broken. Turbopack 109KB polyfill floor.",
			last_commit: null,
		},
		{
			name: "nadavai",
			display_name: "NadavAI",
			path: "~/Desktop/nadavai",
			machine: "Lenovo",
			stack: [
				"Next.js App Router",
				"React",
				"Tailwind",
				"GSAP",
				"Lenis",
				"Motion",
				"next-intl",
				"cmdk",
				"Radix",
			],
			github_repo: "Nadav011/nadavai",
			github_url: "https://github.com/Nadav011/nadavai",
			domain: "nadavc.ai",
			deploy_platform: "Netlify",
			status: "active",
			description_he:
				"אתר פורטפוליו אישי + ויטרינת AI — i18n, GSAP animations, Lenis scroll",
			description_en:
				"Personal portfolio / AI showcase website. i18n, security headers, GSAP + Lenis smooth scroll.",
			default_branch: "main",
			package_manager: "pnpm",
			ci_workflows: [
				"ci.yml",
				"deploy.yml",
				"bundle-check.yml",
				"lighthouse-ci.yml",
				"trivy-autofix.yml",
			],
			features: [
				"i18n (next-intl)",
				"GSAP Animations",
				"Lenis Smooth Scroll",
				"Security Headers",
				"RTL Hebrew",
				"Dark Mode",
			],
			testing: {
				framework: "Vitest 4",
				e2e: undefined,
				mutation: undefined,
				coverage_target: 70,
			},
			bundle_limit_kb: 400,
			security: {
				rls: false,
				csp: true,
				trivy: true,
				semgrep: true,
				gitleaks: true,
			},
			connections: [
				"Netlify (nadavai-portfolio.netlify.app)",
				"Cloudflare DNS (nadavc.ai)",
			],
			supabase_project: undefined,
			related_projects: [],
			notes: "custom domain nadavc.ai — DNS in GoDaddy.",
			last_commit: {
				sha: "c3d4e5f",
				message: "feat: add GSAP scroll animations",
				date: "2026-03-22T14:00:00Z",
			},
		},
		{
			name: "design-system",
			display_name: "Design System",
			path: "~/design-system",
			machine: "Lenovo",
			stack: [
				"Node.js ESM",
				"Style Dictionary 5.3.2",
				"culori",
				"apca-w3",
				"Zod 4.3.6",
				"Vitest",
			],
			github_repo: "Nadav011/design-system",
			github_url: "https://github.com/Nadav011/design-system",
			domain: "",
			deploy_platform: "npm publish",
			status: "active",
			description_he:
				"מערכת עיצוב מולטי-ברנד — 9 מותגים, OKLCH colors, APCA contrast, Style Dictionary v5",
			description_en:
				"Multi-brand design token system serving ALL 9 brands. OKLCH colors, APCA contrast, Style Dictionary v5.",
			default_branch: "main",
			package_manager: "pnpm",
			ci_workflows: ["ci.yml", "trivy-autofix.yml"],
			features: [
				"OKLCH Colors",
				"APCA Contrast",
				"Multi-brand (9 brands)",
				"CSS light/dark tokens",
				"TS/JS tokens",
				"Dart tokens",
			],
			testing: {
				framework: "Vitest",
				e2e: undefined,
				mutation: undefined,
				coverage_target: 70,
			},
			bundle_limit_kb: 0,
			security: {
				rls: false,
				csp: false,
				trivy: true,
				semgrep: false,
				gitleaks: true,
			},
			connections: ["npm registry"],
			supabase_project: undefined,
			related_projects: [
				"mexicani",
				"cash",
				"shifts",
				"hatumdigital",
				"vibechat",
				"sportchat",
				"nadavai",
				"brain",
			],
			notes: "Provides tokens to 9 projects. outputs: CSS, TS/JS, Dart.",
			last_commit: {
				sha: "d4e5f6a",
				message: "feat: add OKLCH color scale for all brands",
				date: "2026-03-18T10:00:00Z",
			},
		},
		{
			name: "my-video",
			display_name: "My Video",
			path: "~/my-video",
			machine: "Lenovo",
			stack: ["Remotion", "Tailwind v4", "Playwright", "Zod"],
			github_repo: "Nadav011/my-video",
			github_url: "https://github.com/Nadav011/my-video",
			domain: "",
			deploy_platform: "",
			status: "active",
			description_he: "יצירת וידאו תכנותית עם React — Remotion",
			description_en:
				"Programmatic video generation with React using Remotion.",
			default_branch: "master",
			package_manager: "pnpm",
			ci_workflows: [],
			features: [
				"Remotion Video",
				"React Components",
				"Tailwind v4",
				"Playwright screenshots",
			],
			testing: {
				framework: undefined,
				e2e: "Playwright",
				mutation: undefined,
				coverage_target: 0,
			},
			bundle_limit_kb: 0,
			security: {
				rls: false,
				csp: false,
				trivy: false,
				semgrep: false,
				gitleaks: false,
			},
			connections: [],
			supabase_project: undefined,
			related_projects: [],
			notes: "branch: master (not main). No CI configured.",
			last_commit: null,
		},
		{
			name: "signature-pro",
			display_name: "Signature Pro",
			path: "~/signature-pro",
			machine: "Lenovo",
			stack: [
				"React 18.3",
				"Vite 5.4",
				"TanStack Query 5.83",
				"Supabase 2.94",
				"Zod 3.25",
				"Tailwind 3.4",
				"Recharts",
				"Embla Carousel",
				"ESLint",
			],
			github_repo: "Nadav011/signature-pro",
			github_url: "https://github.com/Nadav011/signature-pro",
			domain: "signature-pro.pages.dev",
			deploy_platform: "Cloudflare Pages",
			status: "active",
			description_he:
				"עורך חתימות דיגיטליות — תבניות, מדריכים, תשלומים, פאנל אדמין, embed",
			description_en:
				"Digital signature creation/editor — landing page, editor, templates, payment flow, admin panel, embed.",
			default_branch: "main",
			package_manager: "pnpm",
			ci_workflows: [
				"ci.yml",
				"deploy.yml",
				"bundle-check.yml",
				"trivy-autofix.yml",
			],
			features: [
				"Signature Editor",
				"Templates",
				"Payment Flow",
				"Admin Panel",
				"Embed Widget",
				"RTL Hebrew",
			],
			testing: {
				framework: "Vitest",
				e2e: "Playwright+BrowserStack",
				mutation: undefined,
				coverage_target: 70,
			},
			bundle_limit_kb: 400,
			security: {
				rls: true,
				csp: true,
				trivy: true,
				semgrep: true,
				gitleaks: true,
			},
			connections: [
				"Supabase Frankfurt (vjusggkiemcyjxhsnwqv)",
				"Cloudflare Pages",
			],
			supabase_project: "vjusggkiemcyjxhsnwqv",
			related_projects: [],
			notes: "ESLint (not Biome). React 18.3 (not 19). Tailwind 3.4 (not 4).",
			last_commit: {
				sha: "e5f6a7b",
				message: "feat: signature embed widget",
				date: "2026-03-15T12:00:00Z",
			},
		},
		{
			name: "MEX",
			display_name: "MEX",
			path: "~/Desktop/MEX",
			machine: "Lenovo",
			stack: [
				"React",
				"Vite",
				"Base44 SDK",
				"JavaScript (no TS)",
				"Tailwind",
				"Radix",
				"Framer Motion",
				"Stripe",
				"jsPDF",
				"React Quill",
			],
			github_repo: "",
			github_url: "",
			domain: "",
			deploy_platform: "Base44 Platform",
			status: "archived",
			description_he:
				"גרסת Base44 של מקסיקני — ניהול הזמנות, Stripe, Leaflet, Three.js",
			description_en:
				"Mexicani franchise/order management on Base44 platform — Stripe payments, Leaflet maps, Three.js, PDF gen.",
			default_branch: "",
			package_manager: "npm",
			ci_workflows: [],
			features: [
				"Stripe Payments",
				"Leaflet Maps",
				"Three.js",
				"PDF Generation",
				"Rich Text Editor",
			],
			testing: {
				framework: undefined,
				e2e: undefined,
				mutation: undefined,
				coverage_target: 0,
			},
			bundle_limit_kb: 0,
			security: {
				rls: false,
				csp: false,
				trivy: false,
				semgrep: false,
				gitleaks: false,
			},
			connections: ["Base44 SDK", "Stripe"],
			supabase_project: undefined,
			related_projects: ["mexicani"],
			notes:
				"NO GIT. JavaScript only (no TypeScript). Base44 path doubling bug.",
			last_commit: null,
		},
		{
			name: "ai-agent-system",
			display_name: "AI Agent System",
			path: "~/ai-agent-system",
			machine: "Lenovo",
			stack: [
				"Python 3.11+",
				"CrewAI 0.95",
				"LiteLLM",
				"Ollama",
				"ChromaDB",
				"LanceDB",
				"aiogram",
				"Supabase",
				"Playwright",
			],
			github_repo: "",
			github_url: "",
			domain: "",
			deploy_platform: "",
			status: "archived",
			description_he:
				"תזמור סוכני AI לפרודקשן — CrewAI + LLMs מקומיים (Ollama qwen2.5-coder + deepseek-r1)",
			description_en:
				"Production AI agent orchestration — automated code fixes via CrewAI + local LLMs. RTX 3070 optimized.",
			default_branch: "",
			package_manager: "pip",
			ci_workflows: [],
			features: [
				"CrewAI Orchestration",
				"Ollama Local LLMs",
				"ChromaDB Vector Store",
				"LanceDB Memory",
				"Telegram Bot",
				"RTX 3070",
			],
			testing: {
				framework: "pytest",
				e2e: undefined,
				mutation: undefined,
				coverage_target: 0,
			},
			bundle_limit_kb: 0,
			security: {
				rls: false,
				csp: false,
				trivy: false,
				semgrep: false,
				gitleaks: false,
			},
			connections: ["Ollama local", "Supabase", "Telegram", "ChromaDB local"],
			supabase_project: undefined,
			related_projects: [],
			notes: "NO GIT. Superseded by Hydra v2 (LangGraph). RTX 3070 optimized.",
			last_commit: null,
		},
		{
			name: "ai-assistant",
			display_name: "AI Assistant",
			path: "~/ai-assistant",
			machine: "Lenovo",
			stack: [
				"Node.js",
				"WhatsApp Baileys",
				"Discord.js",
				"Telegram Bot",
				"Chrome",
			],
			github_repo: "",
			github_url: "",
			domain: "",
			deploy_platform: "",
			status: "archived",
			description_he:
				"מרכז שליטה AI מקומי — Claude Code דרך WhatsApp/Discord/Telegram, קול עברי",
			description_en:
				"Local AI control hub — Claude Code via WhatsApp/Discord/Telegram. Hebrew voice, browser control.",
			default_branch: "",
			package_manager: "npm",
			ci_workflows: [],
			features: [
				"WhatsApp Control",
				"Discord Bot",
				"Telegram Bot",
				"Hebrew Voice (Ivrit.ai)",
				"Browser Control",
				"systemd Sandbox",
			],
			testing: {
				framework: undefined,
				e2e: undefined,
				mutation: undefined,
				coverage_target: 0,
			},
			bundle_limit_kb: 0,
			security: {
				rls: false,
				csp: false,
				trivy: false,
				semgrep: false,
				gitleaks: false,
			},
			connections: [
				"WhatsApp Baileys",
				"Discord API",
				"Telegram API",
				"Chrome",
			],
			supabase_project: undefined,
			related_projects: [],
			notes: "NO GIT. systemd sandboxed.",
			last_commit: null,
		},
		{
			name: "ai-stack",
			display_name: "AI Stack",
			path: "~/ai-stack",
			machine: "Lenovo",
			stack: [
				"Docker Compose",
				"CUDA",
				"Open WebUI",
				"Ollama",
				"n8n",
				"ChromaDB",
				"Redis",
				"SearXNG",
			],
			github_repo: "",
			github_url: "",
			domain: "",
			deploy_platform: "",
			status: "archived",
			description_he:
				"תשתית AI עצמאית על RTX 3070 — Open WebUI + Ollama + n8n + ChromaDB + Redis + SearXNG",
			description_en:
				"Self-hosted AI infra on RTX 3070 — Open WebUI + Ollama + n8n + ChromaDB + Redis + SearXNG.",
			default_branch: "",
			package_manager: "docker",
			ci_workflows: [],
			features: [
				"Open WebUI",
				"Ollama Local LLMs",
				"n8n Automation",
				"ChromaDB",
				"Redis",
				"SearXNG",
				"CUDA RTX 3070",
			],
			testing: {
				framework: undefined,
				e2e: undefined,
				mutation: undefined,
				coverage_target: 0,
			},
			bundle_limit_kb: 0,
			security: {
				rls: false,
				csp: false,
				trivy: false,
				semgrep: false,
				gitleaks: false,
			},
			connections: [
				"Docker",
				"Ollama local",
				"n8n",
				"Redis local",
				"SearXNG local",
			],
			supabase_project: undefined,
			related_projects: [],
			notes: "NO GIT. OpenRouter cloud fallback. RTX 3070 CUDA.",
			last_commit: null,
		},
		{
			name: "Z",
			display_name: "Z (Cash Control)",
			path: "~/Desktop/Z",
			machine: "MSI",
			stack: [
				"React 18.3",
				"Vite 7.3.1",
				"TanStack Query 5.90.16",
				"Supabase",
				"Capacitor",
				"Tailwind 3.4",
				"Workbox PWA",
				"IndexedDB (idb)",
			],
			github_repo: "Nadav011/Z",
			github_url: "https://github.com/Nadav011/Z",
			domain: "z-cash.pages.dev",
			deploy_platform: "Cloudflare Pages",
			status: "active",
			description_he:
				"PWA ניהול קופה למסעדות — סגירות קופה, הפקדות, פיוס קופה-לבנק",
			description_en:
				"Cash accountability PWA for restaurants — cash closings, deposits, register-to-bank reconciliation.",
			default_branch: "main",
			package_manager: "npm",
			ci_workflows: [
				"ci.yml",
				"deploy.yml",
				"bundle-check.yml",
				"lighthouse-ci.yml",
				"trivy-autofix.yml",
			],
			features: [
				"PWA + Workbox",
				"Offline First",
				"IndexedDB",
				"Capacitor iOS",
				"Dual-persona (managers/cashiers)",
				"RTL Hebrew",
				"iOS-native Design",
			],
			testing: {
				framework: "Vitest 4",
				e2e: undefined,
				mutation: undefined,
				coverage_target: 70,
			},
			bundle_limit_kb: 350,
			security: {
				rls: true,
				csp: true,
				trivy: true,
				semgrep: true,
				gitleaks: true,
			},
			connections: [
				"Supabase Tokyo (svsomygampaxwsfgqtpa)",
				"Cloudflare Pages",
				"Capacitor",
			],
			supabase_project: "svsomygampaxwsfgqtpa",
			related_projects: ["cash", "brain"],
			notes: "npm ONLY (not pnpm). packageManager: npm@10.9.2.",
			last_commit: {
				sha: "f6a7b8c",
				message: "fix: cash closing reconciliation edge case",
				date: "2026-03-25T18:00:00Z",
			},
		},
		{
			name: "cash",
			display_name: "Cash",
			path: "~/Desktop/cash",
			machine: "MSI",
			stack: ["React", "Vite", "Supabase", "Tailwind"],
			github_repo: "Nadav011/cash",
			github_url: "https://github.com/Nadav011/cash",
			domain: "",
			deploy_platform: "Cloudflare Pages",
			status: "archived",
			description_he: "עותק ישן של Z — ארכיבי",
			description_en:
				"Earlier copy of Z (cash-control-app). Z is the active codebase.",
			default_branch: "main",
			package_manager: "pnpm",
			ci_workflows: ["ci.yml", "trivy-autofix.yml"],
			features: ["Cash Management", "RTL Hebrew"],
			testing: {
				framework: "Vitest",
				e2e: undefined,
				mutation: undefined,
				coverage_target: 0,
			},
			bundle_limit_kb: 350,
			security: {
				rls: true,
				csp: false,
				trivy: true,
				semgrep: true,
				gitleaks: true,
			},
			connections: ["Supabase Tokyo (svsomygampaxwsfgqtpa)"],
			supabase_project: "svsomygampaxwsfgqtpa",
			related_projects: ["Z"],
			notes: "Archived — Z is the active codebase.",
			last_commit: null,
		},
		{
			name: "shifts",
			display_name: "Shifts",
			path: "~/Desktop/shifts",
			machine: "MSI",
			stack: [
				"React 19.2.4",
				"Vite 7.3.1",
				"TanStack Query 5.90.21",
				"Supabase 2.97.0",
				"DnD Kit",
				"Workbox PWA",
				"Tailwind 4.2.0",
				"Motion 12",
				"Biome 2.4.4",
			],
			github_repo: "Nadav011/mexicani-shifts",
			github_url: "https://github.com/Nadav011/mexicani-shifts",
			domain: "shifts-8ft.pages.dev",
			deploy_platform: "Cloudflare Pages",
			status: "active",
			description_he:
				"ניהול משמרות מקסיקני — לוח זמנים, משלוחים, ביקורות, הכשרה, נוכחות, שכר",
			description_en:
				"Mexicani shift management — staff scheduling, deliveries, audits, training, attendance, payroll.",
			default_branch: "main",
			package_manager: "pnpm",
			ci_workflows: [
				"ci.yml",
				"deploy.yml",
				"bundle-check.yml",
				"lighthouse-ci.yml",
				"trivy-autofix.yml",
			],
			features: [
				"PWA + Workbox",
				"Offline Persisted",
				"DnD Scheduling",
				"RTL Hebrew",
				"Gold/Glassmorphism Theme",
				"Payroll",
				"Staff Management",
			],
			testing: {
				framework: "Vitest 4",
				e2e: undefined,
				mutation: undefined,
				coverage_target: 70,
			},
			bundle_limit_kb: 400,
			security: {
				rls: true,
				csp: true,
				trivy: true,
				semgrep: true,
				gitleaks: true,
			},
			connections: [
				"Supabase Ireland (ywryfqzgfladpyieveva)",
				"Cloudflare Pages",
			],
			supabase_project: "ywryfqzgfladpyieveva",
			related_projects: ["mexicani"],
			notes:
				"ROLLUP_NATIVE_THREADS=0 needed on MSI. Supabase project name: 'restaurant'.",
			last_commit: {
				sha: "a7b8c9d",
				message: "feat: payroll calculation with overtime",
				date: "2026-03-24T10:00:00Z",
			},
		},
		{
			name: "hatumdigital",
			display_name: "HatumDigital",
			path: "~/Desktop/hatumdigital",
			machine: "MSI",
			stack: [
				"React",
				"Vite",
				"TanStack Query (persisted)",
				"Supabase + Edge Functions",
				"Capacitor iOS",
				"Tailwind",
				"Phosphor Icons",
				"react-window",
				"Framer Motion",
				"Sentry",
			],
			github_repo: "Nadav011/hatumdigital",
			github_url: "https://github.com/Nadav011/hatumdigital",
			domain: "hatumdigital.pages.dev",
			deploy_platform: "Cloudflare Pages",
			status: "active",
			description_he:
				"ניהול הזמנות — מוצרים, הזמנות, לקוחות, הערות, אירועים, תבניות WhatsApp. RTL offline-first",
			description_en:
				"Order management — Products, Orders, Customers, Notes, Events, WhatsApp templates. Hebrew RTL offline-first PWA.",
			default_branch: "main",
			package_manager: "pnpm",
			ci_workflows: [
				"ci.yml",
				"deploy.yml",
				"bundle-check.yml",
				"lighthouse-ci.yml",
				"trivy-autofix.yml",
			],
			features: [
				"PWA Offline-First",
				"Capacitor iOS",
				"RTL Hebrew",
				"Virtualization (react-window)",
				"WhatsApp Templates",
				"Edge Functions",
				"Framer Motion",
			],
			testing: {
				framework: "Vitest+axe",
				e2e: "Playwright 1.58",
				mutation: undefined,
				coverage_target: 70,
			},
			bundle_limit_kb: 400,
			security: {
				rls: true,
				csp: true,
				trivy: true,
				semgrep: true,
				gitleaks: true,
			},
			connections: [
				"Supabase Frankfurt (dmuartcdgbpegbgjuplm)",
				"Cloudflare Pages",
				"Sentry",
				"Capacitor",
			],
			supabase_project: "dmuartcdgbpegbgjuplm",
			related_projects: [],
			notes: "ROLLUP_NATIVE_THREADS=0 needed on MSI.",
			last_commit: {
				sha: "b8c9d0e",
				message: "feat: WhatsApp template builder",
				date: "2026-03-23T14:00:00Z",
			},
		},
		{
			name: "brain",
			display_name: "Brain",
			path: "~/Desktop/brain",
			machine: "MSI",
			stack: [
				"React",
				"Vite",
				"TanStack Query (persisted+sync)",
				"Supabase",
				"Tailwind",
				"Radix",
				"Framer Motion",
				"PWA (Workbox)",
				"IndexedDB",
				"Recharts",
			],
			github_repo: "Nadav011/brain",
			github_url: "https://github.com/Nadav011/brain",
			domain: "brain-3qu.pages.dev",
			deploy_platform: "Cloudflare Pages",
			status: "active",
			description_he:
				"כלי ניהול ידע — custom service workers, integrations, worker threads",
			description_en:
				"Knowledge/brain management tool. Custom service workers, integrations, worker threads.",
			default_branch: "master",
			package_manager: "pnpm",
			ci_workflows: ["ci.yml", "bundle-check.yml", "trivy-autofix.yml"],
			features: [
				"PWA + Workbox",
				"IndexedDB",
				"Offline Sync",
				"Recharts",
				"Framer Motion",
				"Worker Threads",
			],
			testing: {
				framework: "Vitest",
				e2e: undefined,
				mutation: undefined,
				coverage_target: 70,
			},
			bundle_limit_kb: 400,
			security: {
				rls: true,
				csp: false,
				trivy: true,
				semgrep: true,
				gitleaks: true,
			},
			connections: ["Supabase Tokyo (svsomygampaxwsfgqtpa)"],
			supabase_project: "svsomygampaxwsfgqtpa",
			related_projects: ["Z", "cash"],
			notes:
				"branch: master (not main). Shared Supabase with Z/cash. ROLLUP_NATIVE_THREADS=0 on MSI.",
			last_commit: {
				sha: "c9d0e1f",
				message: "feat: worker thread sync engine",
				date: "2026-03-21T08:00:00Z",
			},
		},
		{
			name: "sportchat",
			display_name: "SportChat Ultimate",
			path: "~/Desktop/SportChat/sportchat_ultimate",
			machine: "MSI",
			stack: [
				"Flutter 3.x",
				"Dart >=3.7",
				"Riverpod 3.2.1",
				"GoRouter 15.1",
				"Supabase Flutter 2.8.4",
				"Drift+SQLCipher",
				"Agora RTC 6.5",
				"Firebase Messaging",
				"Dio",
				"Shorebird OTA",
				"Freezed",
				"Sentry Flutter",
			],
			github_repo: "Nadav011/sportchat-ultimate",
			github_url: "https://github.com/Nadav011/sportchat-ultimate",
			domain: "",
			deploy_platform: "App Store + Play Store",
			status: "active",
			description_he:
				"אפליקציית ספורט צ'אט — קול/וידאו (Agora), ניקוד חי (Goalserve), רכישות in-app, ביומטריה, OTA",
			description_en:
				"Diamond-standard sports chat app — real-time voice/video (Agora RTC), live scores (Goalserve), in-app purchases.",
			default_branch: "main",
			package_manager: "flutter pub",
			ci_workflows: ["ci.yml (Flutter)", "trivy-autofix.yml"],
			features: [
				"Real-time Voice/Video (Agora)",
				"Live Scores (Goalserve)",
				"In-app Purchases",
				"Biometric Auth",
				"Shorebird OTA",
				"Encrypted SQLite (SQLCipher)",
				"Push Notifications",
			],
			testing: {
				framework: "very_good test",
				e2e: "Patrol",
				mutation: "glados",
				coverage_target: 80,
			},
			bundle_limit_kb: 0,
			security: {
				rls: true,
				csp: false,
				trivy: false,
				semgrep: false,
				gitleaks: true,
			},
			connections: [
				"Supabase Stockholm (npuifihpwplvrfxsufmu)",
				"Supabase Frankfurt (gpeomchaesuxldtwotmi)",
				"Agora RTC",
				"Firebase Messaging",
				"Goalserve",
				"Shorebird OTA",
			],
			supabase_project: "npuifihpwplvrfxsufmu",
			related_projects: [],
			notes:
				"2 Supabase projects. Flutter: ~/.flutter-sdk/bin/flutter. NEVER flutter test — use very_good test.",
			last_commit: {
				sha: "d0e1f2a",
				message: "feat: Riverpod 3 migration complete",
				date: "2026-03-17T16:00:00Z",
			},
		},
		{
			name: "vibechat",
			display_name: "VibecChat",
			path: "~/Desktop/vibechat",
			machine: "MSI",
			stack: [
				"Next.js",
				"Turborepo",
				"Convex",
				"Clerk Auth",
				"next-intl",
				"Framer Motion",
				"Shiki",
				"Tailwind",
				"Zod",
				"Biome",
			],
			github_repo: "Nadav011/vibechat",
			github_url: "https://github.com/Nadav011/vibechat",
			domain: "",
			deploy_platform: "Netlify",
			status: "active",
			description_he:
				"אפליקציית צ'אט — Turborepo monorepo, Convex real-time, Clerk auth, i18n",
			description_en:
				"Chat app — Turborepo monorepo. Clerk auth, real-time Convex backend, i18n, syntax highlighting.",
			default_branch: "main",
			package_manager: "pnpm",
			ci_workflows: ["ci.yml", "deploy.yml", "trivy-autofix.yml"],
			features: [
				"Turborepo Monorepo",
				"Convex Real-time",
				"Clerk Auth",
				"i18n (next-intl)",
				"Syntax Highlighting (Shiki)",
				"RTL Hebrew",
			],
			testing: {
				framework: "Vitest",
				e2e: undefined,
				mutation: undefined,
				coverage_target: 70,
			},
			bundle_limit_kb: 400,
			security: {
				rls: false,
				csp: true,
				trivy: true,
				semgrep: true,
				gitleaks: true,
			},
			connections: ["Convex (NOT Supabase)", "Clerk Auth", "Netlify"],
			supabase_project: undefined,
			related_projects: [],
			notes:
				"ROLLUP_NATIVE_THREADS=0 on MSI. Convex (not Supabase) — different from all other projects.",
			last_commit: null,
		},
		{
			name: "financeapp",
			display_name: "FinanceApp",
			path: "~/Desktop/FinanceApp",
			machine: "MSI",
			stack: [
				"Expo React Native",
				"Tamagui UI",
				"TanStack Query",
				"expo-camera",
				"expo-localization",
			],
			github_repo: "Nadav011/israeli-finance-app",
			github_url: "https://github.com/Nadav011/israeli-finance-app",
			domain: "",
			deploy_platform: "Mobile (Expo)",
			status: "active",
			description_he: "אפליקציית פיננסים ישראלית — סריקת קבלות, ספריית מדיה",
			description_en:
				"Israeli finance tracker mobile app — receipt scanning, media library.",
			default_branch: "master",
			package_manager: "npm",
			ci_workflows: ["ci.yml", "trivy-autofix.yml"],
			features: [
				"Receipt Scanning",
				"Media Library",
				"RTL Hebrew",
				"expo-camera",
				"i18n (expo-localization)",
			],
			testing: {
				framework: "Jest",
				e2e: undefined,
				mutation: undefined,
				coverage_target: 60,
			},
			bundle_limit_kb: 0,
			security: {
				rls: false,
				csp: false,
				trivy: false,
				semgrep: false,
				gitleaks: true,
			},
			connections: ["Expo EAS"],
			supabase_project: undefined,
			related_projects: [],
			notes: "branch: master (not main). Expo React Native.",
			last_commit: {
				sha: "e1f2a3b",
				message: "feat: receipt scanner camera integration",
				date: "2026-03-10T10:00:00Z",
			},
		},
	],
	total: 18,
	active: 13,
	archived: 4,
	development: 1,
	by_machine: { Lenovo: 8, MSI: 10 },
	by_platform: {
		"Cloudflare Pages": 8,
		Netlify: 3,
		"App Store + Play Store": 1,
		"Mobile (Expo)": 1,
		"npm publish": 1,
		"Base44 Platform": 1,
		"": 4,
	},
	by_stack_type: {
		"React/Vite": 8,
		"Next.js": 3,
		Flutter: 1,
		"React Native": 1,
		Python: 2,
		"Node.js": 2,
		Docker: 1,
		Remotion: 1,
	},
	with_github: 13,
	with_ci: 13,
	with_supabase: 9,
};

// ── Exported STATIC object ────────────────────────────────────────────────────

export const STATIC = {
	agents,
	agentsExternal,
	hydraTasks,
	hydraScores,
	hydraWatcher,
	hydraHealth,
	hooks,
	system,
	metrics,
	memory,
	rules,
	skills,
	mcp,
	openclaw,
	openclawDetails,
	sync,
	lenovoStatus,
	syncStatus,
	crossSync,
	watcherAll,
	notificationsConfig,
	notificationsLog,
	ciStatus,
	ciSummary,
	ciTemplates,
	ciDeep,
	deploysStatus,
	projects,
} as const;
