const CORS_HEADERS = {
	"Content-Type": "application/json",
	"Access-Control-Allow-Origin": "*",
	"Access-Control-Allow-Methods": "GET, OPTIONS",
	Vary: "Origin",
};

export const onRequestGet: PagesFunction = async () => {
	const data = {
		agents: [
			{
				name: "gsd-executor",
				description: "GSD executor agent",
				category: "gsd",
				tools: ["Bash", "Read", "Write", "Edit"],
				file: "gsd-executor.md",
			},
			{
				name: "gsd-planner",
				description: "GSD planner agent",
				category: "gsd",
				tools: ["Bash", "Read", "Write"],
				file: "gsd-planner.md",
			},
			{
				name: "gsd-verifier",
				description: "GSD verifier agent",
				category: "gsd",
				tools: ["Bash", "Read"],
				file: "gsd-verifier.md",
			},
			{
				name: "gsd-debugger",
				description: "GSD debugger agent",
				category: "gsd",
				tools: ["Bash", "Read", "Write"],
				file: "gsd-debugger.md",
			},
			{
				name: "gsd-roadmapper",
				description: "GSD roadmapper agent",
				category: "gsd",
				tools: ["Bash", "Read", "Write"],
				file: "gsd-roadmapper.md",
			},
			{
				name: "gsd-phase-researcher",
				description: "GSD phase researcher",
				category: "gsd",
				tools: ["Bash", "Read"],
				file: "gsd-phase-researcher.md",
			},
			{
				name: "gsd-project-researcher",
				description: "GSD project researcher",
				category: "gsd",
				tools: ["Bash", "Read"],
				file: "gsd-project-researcher.md",
			},
			{
				name: "gsd-plan-checker",
				description: "GSD plan checker",
				category: "gsd",
				tools: ["Read"],
				file: "gsd-plan-checker.md",
			},
			{
				name: "gsd-integration-checker",
				description: "GSD integration checker",
				category: "gsd",
				tools: ["Bash", "Read"],
				file: "gsd-integration-checker.md",
			},
			{
				name: "gsd-codebase-mapper",
				description: "GSD codebase mapper",
				category: "gsd",
				tools: ["Bash", "Read"],
				file: "gsd-codebase-mapper.md",
			},
			{
				name: "gsd-research-synthesizer",
				description: "GSD research synthesizer",
				category: "gsd",
				tools: ["Read", "Write"],
				file: "gsd-research-synthesizer.md",
			},
			{
				name: "code-reviewer",
				description: "L10+ 16-dimension code review",
				category: "quality",
				tools: ["Read", "Bash"],
				file: "code-reviewer.md",
			},
			{
				name: "reality-checker",
				description: "Reality check agent",
				category: "quality",
				tools: ["Bash", "Read"],
				file: "reality-checker.md",
			},
			{
				name: "accessibility",
				description: "Accessibility audit agent",
				category: "quality",
				tools: ["Bash", "Read"],
				file: "accessibility.md",
			},
			{
				name: "api-contract",
				description: "API contract validator",
				category: "quality",
				tools: ["Read", "Bash"],
				file: "api-contract.md",
			},
			{
				name: "edge-case-hunter",
				description: "Edge case discovery agent",
				category: "quality",
				tools: ["Read", "Bash"],
				file: "edge-case-hunter.md",
			},
			{
				name: "security-auditor",
				description: "Security audit agent",
				category: "security",
				tools: ["Bash", "Read", "Write"],
				file: "security-auditor.md",
			},
			{
				name: "agentic-security",
				description: "Agentic security validator",
				category: "security",
				tools: ["Bash", "Read"],
				file: "agentic-security.md",
			},
			{
				name: "dependency-auditor",
				description: "Dependency audit agent",
				category: "security",
				tools: ["Bash", "Read"],
				file: "dependency-auditor.md",
			},
			{
				name: "supabase-auditor",
				description: "Supabase RLS audit agent",
				category: "security",
				tools: ["Bash", "Read"],
				file: "supabase-auditor.md",
			},
			{
				name: "bundle-analyzer",
				description: "Bundle size analyzer",
				category: "performance",
				tools: ["Bash", "Read"],
				file: "bundle-analyzer.md",
			},
			{
				name: "perf-analyzer",
				description: "Performance analyzer",
				category: "performance",
				tools: ["Bash", "Read"],
				file: "perf-analyzer.md",
			},
			{
				name: "db-perf",
				description: "Database performance agent",
				category: "performance",
				tools: ["Bash", "Read"],
				file: "db-perf.md",
			},
			{
				name: "load-test",
				description: "Load testing agent",
				category: "performance",
				tools: ["Bash"],
				file: "load-test.md",
			},
			{
				name: "lighthouse",
				description: "Lighthouse performance audit",
				category: "performance",
				tools: ["Bash", "Read"],
				file: "lighthouse.md",
			},
			{
				name: "test-generator",
				description: "Test generation agent",
				category: "testing",
				tools: ["Read", "Write", "Bash"],
				file: "test-generator.md",
			},
			{
				name: "test-mega",
				description: "Mega test suite agent",
				category: "testing",
				tools: ["Read", "Write", "Bash"],
				file: "test-mega.md",
			},
			{
				name: "race-test",
				description: "Race condition tester",
				category: "testing",
				tools: ["Bash", "Read"],
				file: "race-test.md",
			},
			{
				name: "experiment",
				description: "Experiment runner",
				category: "testing",
				tools: ["Bash", "Read", "Write"],
				file: "experiment.md",
			},
			{
				name: "devops",
				description: "DevOps automation agent",
				category: "infrastructure",
				tools: ["Bash", "Read", "Write", "Edit"],
				file: "devops.md",
			},
			{
				name: "migration",
				description: "Database migration agent",
				category: "infrastructure",
				tools: ["Bash", "Read", "Write"],
				file: "migration.md",
			},
			{
				name: "release-manager",
				description: "Release manager agent",
				category: "infrastructure",
				tools: ["Bash", "Read", "Write"],
				file: "release-manager.md",
			},
			{
				name: "mcp-builder",
				description: "MCP server builder",
				category: "infrastructure",
				tools: ["Read", "Write", "Bash"],
				file: "mcp-builder.md",
			},
			{
				name: "orchestrator",
				description: "Task orchestrator agent",
				category: "infrastructure",
				tools: ["Bash", "Read", "Write"],
				file: "orchestrator.md",
			},
			{
				name: "ci-fixer",
				description: "CI/CD fix agent",
				category: "infrastructure",
				tools: ["Bash", "Read", "Write", "Edit"],
				file: "ci-fixer.md",
			},
			{
				name: "architect",
				description: "System architecture agent",
				category: "analysis",
				tools: ["Read", "Bash", "Write"],
				file: "architect.md",
			},
			{
				name: "autonomous-optimization",
				description: "Autonomous optimization agent",
				category: "analysis",
				tools: ["Bash", "Read", "Write", "Edit"],
				file: "autonomous-optimization.md",
			},
			{
				name: "feedback-synthesizer",
				description: "Feedback synthesis agent",
				category: "analysis",
				tools: ["Read", "Write"],
				file: "feedback-synthesizer.md",
			},
			{
				name: "knowledge-curator",
				description: "Knowledge curation agent",
				category: "analysis",
				tools: ["Read", "Write", "Bash"],
				file: "knowledge-curator.md",
			},
			{
				name: "docs-generator",
				description: "Documentation generator",
				category: "analysis",
				tools: ["Read", "Write"],
				file: "docs-generator.md",
			},
			{
				name: "debugger",
				description: "Debug specialist agent",
				category: "analysis",
				tools: ["Bash", "Read", "Write"],
				file: "debugger.md",
			},
			{
				name: "refactor",
				description: "Code refactor agent",
				category: "analysis",
				tools: ["Read", "Write", "Edit"],
				file: "refactor.md",
			},
			{
				name: "resilience",
				description: "Resilience testing agent",
				category: "analysis",
				tools: ["Bash", "Read"],
				file: "resilience.md",
			},
			{
				name: "ui-ux",
				description: "UI/UX analysis agent",
				category: "analysis",
				tools: ["Read", "Bash", "Write"],
				file: "ui-ux.md",
			},
			{
				name: "rtl-fixer",
				description: "RTL/i18n auto-fix agent",
				category: "general",
				tools: ["Read", "Edit", "Write"],
				file: "rtl-fixer.md",
			},
		],
		external_providers: {
			gemini: {
				available: true,
				model: "gemini-3.1-pro-preview",
				config_exists: true,
				path: "/usr/local/bin/gemini",
			},
			codex: {
				available: true,
				model: "gpt-5.4",
				config_exists: true,
				path: "/usr/local/bin/codex",
			},
			kimi: {
				available: true,
				model: "kimi-k2",
				config_exists: true,
				yolo: true,
				path: "/home/nadavcohen/.local/bin/kimi",
			},
			minimax: {
				available: true,
				model: "MiniMax-M2.7",
				config_exists: true,
				context_k: 204000,
				path: "/home/nadavcohen/.local/bin/minimax",
			},
		},
		total: 45,
	};

	return new Response(JSON.stringify(data), { headers: CORS_HEADERS });
};

export const onRequestOptions: PagesFunction = async () =>
	new Response(null, { status: 204, headers: CORS_HEADERS });
