const CORS_HEADERS = {
	"Content-Type": "application/json",
	"Access-Control-Allow-Origin": "*",
	"Access-Control-Allow-Methods": "GET, OPTIONS",
	Vary: "Origin",
};

export const onRequestGet: PagesFunction = async () => {
	const data = {
		total: 80,
		files_on_disk: 82,
		timing_observability: {
			enabled: true,
			wired_hooks: 3,
			hooks: [
				"post-edit-format.sh",
				"post-edit-typecheck.sh",
				"knowledge-capture.sh",
			],
			description: "Hook execution timing tracked and reported",
		},
		by_event: {
			PreToolUse: 19,
			PostToolUse: 11,
			Stop: 11,
			UserPromptSubmit: 10,
			SessionStart: 8,
			PostCompact: 2,
			SubagentStop: 2,
			PostToolUseFailure: 2,
			PreCompact: 1,
			SessionEnd: 1,
			StopFailure: 1,
			SubagentStart: 1,
			TaskCompleted: 1,
			TaskCreated: 1,
			TeammateIdle: 1,
			PermissionRequest: 1,
			Notification: 1,
			ConfigChange: 1,
			CwdChanged: 1,
			FileChanged: 1,
			InstructionsLoaded: 1,
			WorktreeCreate: 1,
			WorktreeRemove: 1,
		},
		new_events_mar28: [
			"CwdChanged",
			"FileChanged",
			"InstructionsLoaded",
			"SessionEnd",
			"StopFailure",
			"PostCompact",
			"ConfigChange",
			"TaskCreated",
			"WorktreeCreate",
			"WorktreeRemove",
		],
		recent: [
			{
				hook: "anti-premature-completion.sh",
				duration_ms: 12,
				ts: "2026-03-28T10:04:55Z",
			},
			{
				hook: "post-edit-format.sh",
				duration_ms: 45,
				ts: "2026-03-28T10:04:30Z",
			},
			{
				hook: "post-edit-typecheck.sh",
				duration_ms: 820,
				ts: "2026-03-28T10:04:10Z",
			},
			{
				hook: "on-file-changed.sh",
				duration_ms: 6,
				ts: "2026-03-28T10:03:55Z",
			},
			{
				hook: "on-cwd-changed.sh",
				duration_ms: 4,
				ts: "2026-03-28T10:03:50Z",
			},
			{
				hook: "knowledge-capture.sh",
				duration_ms: 22,
				ts: "2026-03-28T10:03:20Z",
			},
		],
		files: [
			"anti-premature-completion.sh",
			"post-compact-reinject.sh",
			"prerequisite-check.sh",
			"post-edit-format.sh",
			"post-edit-typecheck.sh",
			"auto-tmux-dev.sh",
			"check-console-log.sh",
			"tool-guard-hybrid.py",
			"knowledge-capture.sh",
			"correction-detector.sh",
			"dispatch-auto-log.sh",
			"context-compact-guard.py",
			"dispatch-command-guard.sh",
			"session-create-task-file.sh",
			"capture-user-request.sh",
			"on-cwd-changed.sh",
			"on-file-changed.sh",
			"on-instructions-loaded.sh",
			"on-session-end.sh",
			"on-stop-failure.sh",
			"on-task-created.sh",
			"worktree-lifecycle.sh",
			"config-tamper-guard.sh",
			"agent-dispatch-limiter.sh",
			"agent-slot-release.sh",
			"hydra-v2-exec-log.sh",
			"hydra-v2-fallback-retry.sh",
			"hydra-v2-load-scores.sh",
			"hydra-v2-plan-validator.sh",
			"hydra-v2-watcher-health.sh",
			"auap-agent-enricher.sh",
			"auap-session-reminder.sh",
			"auap-subagent-wrapper.sh",
			"stop-verification-gate.sh",
			"reviewer-gate-track.sh",
			"task-completed-gate.sh",
			"subagent-start-inject.sh",
			"subagent-exit-gate.sh",
			"teammate-idle-gate.sh",
			"phone-notify.sh",
			"notification-router.sh",
			"permission-auto-decide.sh",
			"rate-limit-guardian.sh",
			"git-commit-guard.sh",
			"block-main-push.sh",
			"prompt-injection-defender",
		],
	};

	return new Response(JSON.stringify(data), { headers: CORS_HEADERS });
};

export const onRequestOptions: PagesFunction = async () =>
	new Response(null, { status: 204, headers: CORS_HEADERS });
