const CORS_HEADERS = {
	"Content-Type": "application/json",
	"Access-Control-Allow-Origin": "*",
	"Access-Control-Allow-Methods": "GET, OPTIONS",
	Vary: "Origin",
};

export const onRequestGet: PagesFunction = async () => {
	const data = {
		projects: [
			{
				name: "mexicani",
				display_name: "Mexicani",
				path: "~/Desktop/mexicani",
				machine: "pop-os",
				stack: [
					"React 19.2",
					"Vite 7.3",
					"Supabase 2.97",
					"TypeScript 5.9",
					"Tailwind 4.2",
					"TanStack Query 5.90",
					"Capacitor 8.1",
					"Biome 2.4",
					"Zod 4.3",
					"Motion 12",
				],
				github_repo: "Nadav011/Mexicani",
				github_url: "https://github.com/Nadav011/Mexicani",
				domain: "mexicani.pages.dev",
				deploy_platform: "Cloudflare Pages",
				status: "active",
				description_en:
					"Enterprise SaaS franchise management for Mexicani restaurant chain.",
				default_branch: "main",
				package_manager: "pnpm",
				features: [
					"PWA",
					"RTL Hebrew",
					"Offline",
					"Push Notifications",
					"Supabase RLS",
					"Capacitor iOS",
					"i18n",
					"Multi-tenant",
					"39 Edge Functions",
					"228 Migrations",
				],
				testing: {
					framework: "Vitest 4",
					e2e: "Playwright 1.58",
					mutation: "Stryker",
					coverage_target: 80,
				},
				bundle_limit_kb: 450,
				security: {
					rls: true,
					csp: true,
					trivy: true,
					semgrep: true,
					gitleaks: true,
				},
				scale: {
					pages: 149,
					components: 2888,
					hooks: 521,
					lib: 519,
					tables: 115,
					migrations: 228,
					edge_functions: 39,
				},
				last_commit: {
					sha: "a1b2c3d",
					message: "chore: bundle optimization",
					date: "2026-03-26T09:00:00Z",
				},
			},
			{
				name: "chance-pro",
				display_name: "Chance Pro",
				path: "~/Desktop/chance-pro",
				machine: "pop-os",
				stack: [
					"Python 3.10+",
					"NumPy >=2.4",
					"SciPy >=1.17",
					"SQLite",
					"Static HTML",
				],
				github_repo: "Nadav011/chance-pro",
				github_url: "https://github.com/Nadav011/chance-pro",
				domain: "chance-pro.pages.dev",
				deploy_platform: "Cloudflare Pages",
				status: "active",
				description_en:
					"Advanced statistical dashboard for Israeli Pais Chance lottery. 49,533+ draws, 31 algorithms.",
				default_branch: "main",
				package_manager: "pip",
				features: [
					"Bayesian Statistics",
					"Monte Carlo",
					"CUSUM",
					"Entropy Analysis",
					"5 Games",
					"49,533+ Draws",
				],
				testing: {
					framework: "pytest",
					mutation: "mutmut",
					coverage_target: 70,
				},
				bundle_limit_kb: 0,
				security: {
					rls: false,
					csp: false,
					trivy: true,
					semgrep: true,
					gitleaks: true,
				},
				last_commit: {
					sha: "b2c3d4e",
					message: "feat: add entropy analysis",
					date: "2026-03-20T10:00:00Z",
				},
			},
			{
				name: "mediflow",
				display_name: "MediFlow",
				path: "~/Desktop/mediflow",
				machine: "pop-os",
				stack: [
					"Next.js 16.1",
					"React Compiler",
					"Supabase SSR",
					"CipherStash Protect",
					"TanStack Query",
					"Zod 4",
					"Tailwind 4.x",
					"Pino",
					"Sentry",
					"Biome 2.x",
				],
				github_repo: "",
				github_url: "",
				domain: "mediflow.netlify.app",
				deploy_platform: "Netlify (broken)",
				status: "development",
				description_en:
					"Israeli Medical Platform — ISO 27001/27799 + Amendment 13. Medical records with break-the-glass emergency access.",
				default_branch: "main",
				package_manager: "pnpm",
				features: [
					"ISO 27001/27799",
					"Amendment 13",
					"Field-level Encryption",
					"Break-the-glass Access",
					"RTL Hebrew",
					"Supabase SSR",
				],
				testing: {
					framework: "Vitest 4",
					e2e: "Playwright 1.58",
					coverage_target: 80,
				},
				bundle_limit_kb: 300,
				security: {
					rls: true,
					csp: true,
					trivy: true,
					semgrep: true,
					gitleaks: true,
				},
				last_commit: null,
			},
			{
				name: "nadavai",
				display_name: "NadavAI",
				path: "~/Desktop/nadavai",
				machine: "pop-os",
				stack: [
					"Next.js App Router",
					"React",
					"Tailwind",
					"GSAP",
					"Lenis",
					"Motion",
					"next-intl",
					"cmdk",
					"Radix",
				],
				github_repo: "Nadav011/nadavai",
				github_url: "https://github.com/Nadav011/nadavai",
				domain: "nadavc.ai",
				deploy_platform: "Netlify",
				status: "active",
				description_en:
					"Personal portfolio / AI showcase website. i18n, security headers, GSAP + Lenis smooth scroll.",
				default_branch: "main",
				package_manager: "pnpm",
				features: [
					"i18n",
					"GSAP Animations",
					"Lenis Scroll",
					"Security Headers",
					"RTL Hebrew",
				],
				testing: {
					framework: "Vitest 4",
					e2e: "Playwright 1.58",
					coverage_target: 70,
				},
				bundle_limit_kb: 250,
				security: {
					rls: false,
					csp: true,
					trivy: true,
					semgrep: true,
					gitleaks: true,
				},
			},
			{
				name: "Z",
				display_name: "Z (Cash Control)",
				path: "~/Desktop/Z",
				machine: "lenovo",
				stack: ["React 18", "Vite", "npm"],
				github_repo: "Nadav011/Z",
				github_url: "https://github.com/Nadav011/Z",
				domain: "z-cash.pages.dev",
				deploy_platform: "Cloudflare Pages",
				status: "active",
				description_en: "Personal finance tracking app.",
				default_branch: "main",
				package_manager: "npm",
				features: ["RTL Hebrew", "Supabase"],
				security: {
					rls: true,
					csp: false,
					trivy: true,
					semgrep: true,
					gitleaks: true,
				},
			},
			{
				name: "shifts",
				display_name: "Mexicani Shifts",
				path: "~/Desktop/shifts",
				machine: "lenovo",
				stack: ["React 19", "Vite", "Supabase", "TypeScript"],
				github_repo: "Nadav011/mexicani-shifts",
				github_url: "https://github.com/Nadav011/mexicani-shifts",
				domain: "mexicani-shifts.pages.dev",
				deploy_platform: "Cloudflare Pages",
				status: "active",
				description_en:
					"Employee shifts management for Mexicani restaurant chain.",
				default_branch: "main",
				package_manager: "pnpm",
				features: ["RTL Hebrew", "Supabase RLS", "PWA"],
				security: {
					rls: true,
					csp: true,
					trivy: true,
					semgrep: true,
					gitleaks: true,
				},
			},
			{
				name: "hatumdigital",
				display_name: "HatumDigital",
				path: "~/Desktop/hatumdigital",
				machine: "lenovo",
				stack: ["React", "Vite", "Capacitor"],
				github_repo: "Nadav011/hatumdigital",
				github_url: "https://github.com/Nadav011/hatumdigital",
				domain: "hatumdigital.pages.dev",
				deploy_platform: "Cloudflare Pages",
				status: "active",
				description_en: "Mobile-first web app with Capacitor native wrapper.",
				default_branch: "main",
				package_manager: "pnpm",
				features: ["Capacitor", "RTL Hebrew", "PWA"],
				security: {
					rls: false,
					csp: false,
					trivy: true,
					semgrep: true,
					gitleaks: true,
				},
			},
			{
				name: "brain",
				display_name: "Brain",
				path: "~/Desktop/brain",
				machine: "lenovo",
				stack: ["React", "Vite", "TypeScript"],
				github_repo: "Nadav011/brain",
				github_url: "https://github.com/Nadav011/brain",
				domain: "brain.pages.dev",
				deploy_platform: "Cloudflare Pages",
				status: "active",
				description_en: "Personal knowledge management app.",
				default_branch: "master",
				package_manager: "pnpm",
				features: ["RTL Hebrew"],
				security: {
					rls: false,
					csp: false,
					trivy: true,
					semgrep: false,
					gitleaks: true,
				},
			},
			{
				name: "SportChat",
				display_name: "SportChat",
				path: "~/Desktop/SportChat/sportchat_ultimate",
				machine: "lenovo",
				stack: [
					"Flutter 3.41",
					"Dart 3.11",
					"Riverpod 3.2",
					"go_router 14",
					"Firebase",
					"Supabase",
					"ZegoUIKit",
				],
				github_repo: "Nadav011/sportchat-ultimate",
				github_url: "https://github.com/Nadav011/sportchat-ultimate",
				domain: "",
				deploy_platform: "App Store / Google Play",
				status: "active",
				description_en:
					"Sports social chat app — Flutter, Riverpod 3, real-time messaging, voice/video calls.",
				default_branch: "main",
				package_manager: "pub",
				features: [
					"Real-time Chat",
					"Voice/Video Calls",
					"Push Notifications",
					"Deep Links",
					"RTL",
				],
				testing: {
					framework: "very_good_cli",
					mutation: "mutation_test",
					coverage_target: 75,
				},
				security: {
					rls: true,
					csp: false,
					trivy: false,
					semgrep: false,
					gitleaks: true,
				},
			},
			{
				name: "vibechat",
				display_name: "VibChat",
				path: "~/Desktop/vibechat",
				machine: "lenovo",
				stack: ["Next.js", "Convex", "TypeScript", "Tailwind"],
				github_repo: "Nadav011/vibechat",
				github_url: "https://github.com/Nadav011/vibechat",
				domain: "",
				deploy_platform: "Cloudflare Pages",
				status: "development",
				description_en: "Real-time chat platform built with Convex.",
				default_branch: "main",
				package_manager: "pnpm",
				features: ["Real-time", "Convex DB"],
				security: {
					rls: false,
					csp: false,
					trivy: true,
					semgrep: true,
					gitleaks: true,
				},
			},
			{
				name: "design-system",
				display_name: "Design System",
				path: "~/design-system",
				machine: "pop-os",
				stack: ["Node ESM", "Style Dictionary"],
				github_repo: "Nadav011/design-system",
				github_url: "https://github.com/Nadav011/design-system",
				domain: "",
				deploy_platform: "npm",
				status: "active",
				description_en: "Shared design tokens and component primitives.",
				default_branch: "main",
				package_manager: "pnpm",
				features: ["Design Tokens", "Style Dictionary", "RTL Support"],
				security: {
					rls: false,
					csp: false,
					trivy: true,
					semgrep: false,
					gitleaks: true,
				},
			},
			{
				name: "my-video",
				display_name: "My Video",
				path: "~/my-video",
				machine: "pop-os",
				stack: ["Remotion", "React", "TypeScript"],
				github_repo: "Nadav011/my-video",
				github_url: "https://github.com/Nadav011/my-video",
				domain: "",
				deploy_platform: "Render",
				status: "active",
				description_en: "Programmatic video generation with Remotion.",
				default_branch: "master",
				package_manager: "pnpm",
				features: ["Programmatic Video", "React"],
				security: {
					rls: false,
					csp: false,
					trivy: false,
					semgrep: false,
					gitleaks: false,
				},
			},
			{
				name: "signature-pro",
				display_name: "Signature Pro",
				path: "~/signature-pro",
				machine: "pop-os",
				stack: ["React 18", "Vite", "TypeScript"],
				github_repo: "Nadav011/signature-pro",
				github_url: "https://github.com/Nadav011/signature-pro",
				domain: "signature-pro.pages.dev",
				deploy_platform: "Cloudflare Pages",
				status: "active",
				description_en: "Email signature generator.",
				default_branch: "main",
				package_manager: "pnpm",
				features: ["RTL Hebrew", "Export"],
				security: {
					rls: false,
					csp: false,
					trivy: true,
					semgrep: true,
					gitleaks: true,
				},
			},
			{
				name: "FinanceApp",
				display_name: "Israeli Finance App",
				path: "~/Desktop/FinanceApp",
				machine: "lenovo",
				stack: ["Expo", "React Native", "TypeScript"],
				github_repo: "Nadav011/israeli-finance-app",
				github_url: "https://github.com/Nadav011/israeli-finance-app",
				domain: "",
				deploy_platform: "App Store / Google Play",
				status: "development",
				description_en: "Israeli personal finance mobile app built with Expo.",
				default_branch: "master",
				package_manager: "pnpm",
				features: ["RTL Hebrew", "Expo", "React Native"],
				security: {
					rls: false,
					csp: false,
					trivy: true,
					semgrep: false,
					gitleaks: true,
				},
			},
			{
				name: "MEX",
				display_name: "MEX",
				path: "~/Desktop/MEX",
				machine: "pop-os",
				stack: ["Base44", "React JS"],
				github_repo: "",
				domain: "",
				deploy_platform: "Base44",
				status: "active",
				description_en: "Base44 rapid-prototype version of Mexicani.",
				default_branch: "",
				package_manager: "npm",
			},
			{
				name: "ai-agent-system",
				display_name: "AI Agent System",
				path: "~/ai-agent-system",
				machine: "pop-os",
				stack: ["Python", "CrewAI"],
				github_repo: "",
				domain: "",
				deploy_platform: "local",
				status: "active",
				description_en: "Multi-agent AI orchestration system.",
				default_branch: "",
				package_manager: "pip",
			},
			{
				name: "ai-assistant",
				display_name: "AI Assistant",
				path: "~/ai-assistant",
				machine: "pop-os",
				stack: ["Node.js"],
				github_repo: "",
				domain: "",
				deploy_platform: "local",
				status: "active",
				description_en: "Personal AI assistant server.",
				default_branch: "",
				package_manager: "npm",
			},
			{
				name: "ai-stack",
				display_name: "AI Stack",
				path: "~/ai-stack",
				machine: "pop-os",
				stack: ["Docker"],
				github_repo: "",
				domain: "",
				deploy_platform: "local",
				status: "active",
				description_en: "Docker compose AI services stack.",
				default_branch: "",
				package_manager: "docker",
			},
		],
		total: 18,
	};

	return new Response(JSON.stringify(data), { headers: CORS_HEADERS });
};

export const onRequestOptions: PagesFunction = async () =>
	new Response(null, { status: 204, headers: CORS_HEADERS });
