const CORS_HEADERS = {
	"Content-Type": "application/json",
	"Access-Control-Allow-Origin": "*",
	"Access-Control-Allow-Methods": "GET, OPTIONS",
	Vary: "Origin",
};

export const onRequestGet: PagesFunction = async () => {
	const data = {
		total: 86,
		categories: {
			code: 12,
			ui: 10,
			test: 9,
			security: 8,
			devops: 7,
			review: 6,
			flutter: 6,
			frontend: 5,
			backend: 5,
			ai: 5,
			mobile: 5,
			docs: 4,
			orchestration: 6,
		},
		plugins_count: 19,
		conductor_skills: {
			count: 6,
			list: [
				"conductor-setup",
				"conductor-implement",
				"conductor-review",
				"conductor-revert",
				"conductor-newTrack",
				"conductor-status",
			],
		},
		new_mar28: [
			"conductor-setup",
			"conductor-implement",
			"conductor-review",
			"conductor-revert",
			"conductor-newTrack",
			"conductor-status",
			"rtl-fix",
			"deep-project",
			"deep-plan",
			"deep-implement",
			"superpowers",
			"claude-mem",
		],
		skills_list: [
			"code-reviewer",
			"adversarial-review",
			"reality-checker",
			"edge-case-hunter",
			"brainstorming",
			"implement-playground",
			"ui-shadcn",
			"security-rules",
			"flutter-rules",
			"testing-rules",
			"frontend-rules",
			"backend-rules",
			"ai-rules",
			"devops-rules",
			"mobile-mastery",
			"mobile-upgrade-2026",
			"a11y",
			"distillator",
			"shard-doc",
			"nuclear",
			"pdf",
			"commit",
			"review-pr",
			"harness-audit",
			"advanced-elicitation",
			"pwa-expert",
			"ui-colors",
			"ui-reactbits",
			"ui-icons",
			"flutter-audit",
			"conductor",
			"rtl-fix",
			"rtl-validator",
			"deep-project",
			"deep-plan",
			"deep-implement",
			"superpowers",
			"claude-mem",
			"apex-core-rules",
			"apex-guards",
			"apex-sec",
			"apex-coverage",
			"apex-init",
			"apex-prime",
			"conductor-setup",
			"conductor-implement",
			"conductor-review",
			"conductor-revert",
			"conductor-newTrack",
			"conductor-status",
			"gsd:autonomous",
			"gsd:do",
			"gsd:quick",
			"dispatch",
			"auap",
			"team",
			"agent-audit",
			"hook-doctor",
			"hydra",
			"hydra-arena",
			"hydra-debate",
			"hydra-status",
			"load-test",
			"resilience-test",
			"race-test",
			"visual-regression",
			"integration-test",
			"perf-expert",
			"perf",
			"bundle-analyze",
			"deps-audit",
			"owasp-security",
			"rls-check",
			"db-perf",
			"e2e",
			"test-mega",
			"test-gen",
			"unit",
			"coverage",
			"zod-patterns",
			"nextjs-patterns",
			"flutter-state",
			"flutter-patterns",
			"flutter-arch",
			"modernize",
			"clean",
			"quick-fix",
			"simplify",
			"save-session",
			"emergency",
			"diagnose",
		],
	};

	return new Response(JSON.stringify(data), { headers: CORS_HEADERS });
};

export const onRequestOptions: PagesFunction = async () =>
	new Response(null, { status: 204, headers: CORS_HEADERS });
