const CORS_HEADERS = {
	"Content-Type": "application/json",
	"Access-Control-Allow-Origin": "https://hydra-dashboard.pages.dev",
	"Access-Control-Allow-Methods": "GET, OPTIONS",
	Vary: "Origin",
};

export const onRequestGet: PagesFunction = async () => {
	const data = {
		pipeline: [
			{ name: "install", jobs: ["pnpm install --frozen-lockfile"] },
			{
				name: "quality",
				jobs: [
					"typecheck",
					"lint (Biome 2.4.4)",
					"semgrep",
					"trivy",
					"gitleaks",
					"socket-ci",
				],
				duration_estimate: "2-4 min",
			},
			{
				name: "test",
				jobs: [
					"vitest --maxWorkers=2 --shard=1/4",
					"vitest --maxWorkers=2 --shard=2/4",
					"vitest --maxWorkers=2 --shard=3/4",
					"vitest --maxWorkers=2 --shard=4/4",
				],
				duration_estimate: "3-8 min",
			},
			{ name: "lighthouse", jobs: ["lhci autorun"] },
			{ name: "build", jobs: ["pnpm build"] },
			{
				name: "deploy",
				jobs: ["CF Pages / Netlify deploy"],
				duration_estimate: "1-3 min",
			},
		],
		tools: [
			{
				name: "Biome",
				version: "2.4.4",
				category: "quality",
				command: "biome check . --apply",
				purpose: "Linting + formatting",
				blocking: true,
				docs_url: "https://biomejs.dev",
			},
			{
				name: "Vitest",
				version: "4.0.18",
				category: "testing",
				command: "vitest --maxWorkers=2",
				purpose: "Unit + integration tests",
				blocking: true,
			},
			{
				name: "Playwright",
				version: "1.58.2",
				category: "testing",
				command: "playwright test",
				purpose: "E2E browser tests",
				blocking: true,
			},
			{
				name: "trivy",
				version: "0.69.3",
				category: "security",
				command: "trivy fs . --severity HIGH,CRITICAL",
				purpose: "CVE scanning",
				blocking: true,
				docs_url: "https://aquasecurity.github.io/trivy",
			},
			{
				name: "semgrep",
				version: "1.155.0",
				category: "security",
				command: "semgrep scan . --config=auto",
				purpose: "SAST / OWASP scanning",
				blocking: true,
			},
			{
				name: "gitleaks",
				version: "latest",
				category: "security",
				command: ".github/workflows (auto)",
				purpose: "Secret detection",
				blocking: true,
			},
			{
				name: "socket",
				version: "1.1.73",
				category: "security",
				command: "socket npm install <pkg>",
				purpose: "Supply chain security",
				blocking: false,
			},
			{
				name: "Lighthouse CI",
				version: "0.15.1",
				category: "perf",
				command: "lhci autorun",
				purpose: "Performance audits",
				blocking: false,
			},
			{
				name: "k6",
				version: "1.6.1",
				category: "perf",
				command: "k6 run tests/load/test.js",
				purpose: "Load testing",
				blocking: false,
			},
			{
				name: "git-cliff",
				version: "2.12.0",
				category: "dev",
				command: "git-cliff -o CHANGELOG.md",
				purpose: "Changelog generation",
				blocking: false,
			},
			{
				name: "type-coverage",
				version: "2.29.7",
				category: "quality",
				command: "type-coverage --at-least 90 --detail",
				purpose: "TypeScript any% detection",
				blocking: false,
			},
			{
				name: "knip",
				version: "5.86.0",
				category: "quality",
				command: "knip",
				purpose: "Dead code detection",
				blocking: false,
			},
			{
				name: "act",
				version: "0.2.84",
				category: "dev",
				command: "act push",
				purpose: "Local CI debug",
				blocking: false,
			},
			{
				name: "hurl",
				version: "7.1.0",
				category: "testing",
				command: "hurl tests/api/",
				purpose: "API testing",
				blocking: false,
			},
		],
		reusable_workflows: {
			repo: "Nadav011/ci-standards",
			workflows: [
				{
					file: "ci-vite-react.yml",
					name: "CI — Vite + React",
					description: "Full CI for Vite + React projects",
					triggers: ["push", "pull_request"],
					jobs: [
						"typecheck",
						"lint",
						"semgrep",
						"trivy",
						"gitleaks",
						"test",
						"build",
					],
					secrets_required: ["SUPABASE_URL", "SUPABASE_ANON_KEY"],
					repos_using: 7,
				},
				{
					file: "ci-nextjs.yml",
					name: "CI — Next.js",
					description: "Full CI for Next.js projects",
					triggers: ["push", "pull_request"],
					jobs: [
						"typecheck",
						"lint",
						"semgrep",
						"trivy",
						"gitleaks",
						"test",
						"build",
					],
					secrets_required: ["SUPABASE_URL", "SUPABASE_ANON_KEY"],
					repos_using: 3,
				},
				{
					file: "ci-flutter.yml",
					name: "CI — Flutter",
					description: "CI for Flutter/Dart projects",
					triggers: ["push", "pull_request"],
					jobs: ["analyze", "test", "build"],
					secrets_required: ["FIREBASE_CONFIG"],
					repos_using: 1,
				},
			],
		},
		github_apps: [
			{
				name: "Renovate",
				purpose: "Weekly dependency update PRs",
				installed_on: [
					"Mexicani",
					"mexicani-shifts",
					"Z",
					"hatumdigital",
					"brain",
					"vibechat",
					"sportchat-ultimate",
					"nadavai",
					"signature-pro",
					"chance-pro",
					"design-system",
					"my-video",
					"israeli-finance-app",
				],
				auto_pr: true,
				webhook_events: ["push"],
			},
			{
				name: "Socket.dev",
				purpose: "Supply chain security checks",
				installed_on: [
					"Mexicani",
					"mexicani-shifts",
					"Z",
					"hatumdigital",
					"brain",
					"vibechat",
					"sportchat-ultimate",
					"nadavai",
					"signature-pro",
					"chance-pro",
					"design-system",
					"my-video",
					"israeli-finance-app",
				],
				auto_pr: false,
				webhook_events: ["pull_request"],
			},
			{
				name: "CodeRabbit",
				purpose: "AI automated code review",
				installed_on: [
					"Mexicani",
					"mexicani-shifts",
					"Z",
					"hatumdigital",
					"brain",
					"vibechat",
					"sportchat-ultimate",
					"nadavai",
					"signature-pro",
					"chance-pro",
					"design-system",
					"my-video",
					"israeli-finance-app",
				],
				auto_pr: false,
				webhook_events: ["pull_request"],
			},
		],
		security_gates: [
			{
				name: "harden-runner",
				tool: "step-security/harden-runner@v2.16.0",
				blocking: true,
				severity_threshold: "critical",
				notes: "CVE-2026-25598 + GHSA-g699 patched — pin to v2.16.0",
			},
			{
				name: "trivy-action",
				tool: "aquasecurity/trivy-action@<SHA>",
				blocking: true,
				severity_threshold: "HIGH",
				notes: "SHA-pinned — 75/76 tags compromised March 2026",
			},
			{
				name: "attest-build-provenance",
				tool: "actions/attest-build-provenance@v4",
				blocking: false,
				notes: "SLSA v4 provenance",
			},
			{
				name: "cancel-in-progress",
				tool: "concurrency.cancel-in-progress",
				blocking: false,
				notes: "true for CI, false for deploy",
			},
			{
				name: "runs-on",
				tool: "[self-hosted, linux, x64, pop-os]",
				blocking: true,
				notes: "NEVER ubuntu-latest",
			},
			{
				name: "needs: ci-gate",
				tool: "deploy.yml needs: [ci-gate]",
				blocking: true,
				notes: "deploy must depend on ci-gate",
			},
		],
		runners: [
			{
				label: "[self-hosted, linux, x64, pop-os]",
				machine: "pop-os",
				ip: "100.82.33.122",
				cores: 24,
				ram_gb: 64,
				count: 17,
				status: "online",
				total: 22,
			},
			{
				label: "[self-hosted, linux, x64, lenovo]",
				machine: "Lenovo",
				ip: "100.87.247.87",
				cores: 12,
				ram_gb: 32,
				count: 5,
				status: "online",
			},
		],
		stats: {
			total_repos: 14,
			repos_with_ci: 13,
			total_workflow_files: 196,
			total_tools: 14,
			total_security_gates: 6,
			total_runners: 22,
			total_reusable_workflows: 3,
			github_apps: 3,
			projects_with_ci: 13,
			projects_total: 14,
		},
	};

	return new Response(JSON.stringify(data), { headers: CORS_HEADERS });
};

export const onRequestOptions: PagesFunction = async () =>
	new Response(null, { status: 204, headers: CORS_HEADERS });
